### ISSUE TITLE
Auto healing from randomized resources parallel deleting

### ISSUE THREAD

**Issue by kyuho24** [kubernetes-sigs/cluster-api-provider-azure#1090]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When I delete the resource group in Azure portal, CAPZ fail to recover.
- CAPZ only retry to build/update network resource (LB, NSG, Public IP, VNET).
- CAPZ not try to build/update VMs
- observation for 3 days

**What did you expect to happen:**
When I deleted an egress rule, CPAZ rebuilt very fast (almost 5 sec)
But when I deleted the resource group, CAPZ fails to recover the cluster.
My guesses.
- Azure portal's resource delete sequence is according to azure's internal dynamic algorithm (it means apply different sequence when it is issued)
- CAPZ has some dependency rules but it doesn't cover this conner case
- this conner case(assumption): CAPZ health check algorithm finds some network resource failure first, And tries to rebuild it. At the same time, VMs are deleted. CAPZ continue to  resolve LB failure, that time CAPZ can't find the target backend pool(VMs). CAPZ starts to start infinity war.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- clusterctl cli version : 0.3.10
- Cluster API verison: v1alpha3
- cluster (by CAPZ) version : 1.19.0
- admin cluster : 1.18.4

**Comment by CecileRobertMichon** [comment]
Hi @kyuho24, thanks for opening this issue. The VMs not getting recreated is desired behavior as the machines are immutable by design (see https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1008). However, if you add [machine health checks](https://cluster-api.sigs.k8s.io/tasks/healthcheck.html), cluster api will auto remediate by replacing machines that are in a failed state (missing vm). Control planes should also be remediated with a machine health check as support was [recently added](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v0.3.11). Note that you’ll need to set maxUnavailable to 100% if you want the cluster to remediate when all machines are down.

**Comment by kyuho24** [comment]
Thanks @CecileRobertMichon. 
Is "DON'T recreate VMs policy" a general policy fo native Cluster API design? or only for CAPZ ?
And Cloud you explain why CAPZ(or general cluster API) prohibits to recreate VMs ?

**Comment by CecileRobertMichon** [comment]
@kyuho24 it is a Cluster API design concept. See https://cluster-api.sigs.k8s.io/user/concepts.html?highlight=immu#machine-immutability-in-place-upgrade-vs-replace and https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20181121-machine-api.md#in-place-vs-replace.

You bring up a good point about what should happen if the user manually deletes all Azure resources (and I don't believe this issue is specific to CAPZ, all infrastructure providers face a similar one). It is indeed strange to end up in a state where network resources are recreated but the cluster stays down because no VMs are recreated. However, in order to bring back the control plane, we would have to re-initialize it from a kubeadm perspective since no new control plane machines would be able to join the existing control plane as it would be down. As a user what behavior would you expect in this situation? A clear error message requiring you to create a new cluster or some sort of remediation, even if that means bringing up an entirely new cluster?

@nader-ziada do you have any thoughts on this?

**Comment by nader-ziada** [comment]
This is my understanding: if the VM is deleted outside of cluster-api, its not always recoverable because for example the disk could still be present and that would lead to a failure when creating the vm, and since its not guaranteed capz would be able to create the VM again based on what resources are present and what is deleted, the behaviour is to set the `Machine` status to `Failed` and leave it at that for human intervention. I believe this is the same with all cluster-api providers.
