### ISSUE TITLE
Pass credentials into manager via a file instead of environment variables

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-azure#1112]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I've been reviewing the [Draft DISA STIG for Kubernetes](https://public.cyber.mil/announcement/request-for-comments-disa-has-released-the-draft-kubernetes-stig-for-review/), and CNTR-K8-001160 states:

> "Secrets in Kubernetes must not be stored as environment variables."
> ""On the Kubernetes m. node, run the following command:
> kubectl get all -o jsonpath='{range .items[?(@..secretKeyRef)]} {.kind} {.metadata.name} {""\n""}{end}' -A
> If any of the values returned reference environment variables, this is a finding."

The language isn't the best (I have also requested they remove the offensive text), but I believe this is another restatement of not using env vars for secrets as they can be accessed via the /proc filesystem.

Would it be possible to move this to loading credentials from a file?

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 0.4.10
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by CecileRobertMichon** [comment]
@randomvariable does CAPA already pass in credentials via a file?

**Comment by randomvariable** [comment]
Yup, more accurately, it follows the SDK rules so we write the secret to ~/.aws/credentials

**Comment by CecileRobertMichon** [comment]
Note that this is _partially_ solved by [multi-tenancy](https://capz.sigs.k8s.io/topics/multitenancy.html) as credentials will now be created as secrets instead of being passed into the manager, but the default manager still requires passing in credentials. This should change in v1alpha4 when the default becomes one identity per AzureCluster.

In the meantime, trying to see how we could use a file instead of environment variables to pass creds to the manager but I'm not sure that would play well with clusterctl. Doesn't CAPA also pass in credentials directly as an env var in `AWS_B64ENCODED_CREDENTIALS` @randomvariable ?
