### ISSUE TITLE
Clusters names starting with a number char are not allowed by the webhook

### ISSUE THREAD

**Issue by fiunchinho** [kubernetes-sigs/cluster-api-provider-azure#1179]
/kind bug

**What steps did you take and what happened:**

Trying to create an `AzureCluster` CR named `1a2b3c` is not allowed, the webhook will prevent it, failing with 

```Cluster Name doesn't match regex ^[a-z][a-z0-9-]{0,44}[a-z0-9]$, can contain only lowercase alphanumeric characters and '-', must start/end with an alphanumeric character```

But the explanation and the regex don't match. While the explanation says names "_must start/end with an alphanumeric character_", the regex doesn't allow the cluster name to start with a number. I don't see any reason why a cluster name wouldn't start with a number, so I guess this is a bug in the regex. I can submit a PR changing the regex to `^[a-z0-9][a-z0-9-]{0,44}[a-z0-9]$` but I wanted to run it by you first.

**What did you expect to happen:**

When creating a cluster named ``1a2b3c``, cluster validation in admission controller webhook is successful and cluster is created.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
I think that's fine, looking at https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules, I don't see any resources that we use that can't start with a number. The regex was originally added in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/828 to allow defaulting resource names using the cluster name as prefix without breaking Azure naming rules. 

The only concern I have here is that this could potentially be a breaking change for round trip conversions (eg. v1alpha4 -> v1alpha3) but since we're still in alpha and this should only be a rare use case we can accept that as long as it's documented in release notes.
