### ISSUE TITLE
Add integration test for Kubernetes

### ISSUE THREAD

**Issue by vannrt** [kubernetes-sigs/cluster-api-provider-azure#12]
The integration tests at the moment aren't covering Kubernetes functionality. Maybe add Kubernetes conformance tests as part of an integration test? Use https://github.com/heptio/sonobuoy

**Comment by CecileRobertMichon** [comment]
I think this issue is partially "done" now that we have conformance running as a periodic job with https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#periodic-conformance-v1alpha3  using https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/scripts/ci-conformance.sh.

The remaining TODOs I see are: 
- figure out what to do with https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/master/test/integration (it's running as a presubmit but the test suite is empty)
- extend capi framework to run conformance https://github.com/kubernetes-sigs/cluster-api/issues/2826
- maybe use sonobuoy instead of building the e2e binaries directly from k/k
