### ISSUE TITLE
Add validations to AzureMachineTemplate to enforce immutability

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1255]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Issue came from this slack discussion: https://kubernetes.slack.com/archives/CEX9HENG7/p1616445246083000 

As documented in https://cluster-api.sigs.k8s.io/tasks/change-machine-template.html
> These MachineTemplate resources should be immutable, unless the infrastructure provider documentation indicates otherwise for certain fields (see below for more details).

> Some infrastructure providers may, at their discretion, choose to support in-place modifications of certain infrastructure machine template fields. This may be useful if an infrastructure provider is able to make changes to running instances/machines, such as updating allocated memory or CPU capacity. In such cases, however, Cluster API will not trigger a rolling update.

Currently, updates to AzureMachineTemplates are allowed which is misleading as it results in no changes being applied to the running AzureMachines and no rolling update being triggered. We should block updates and instruct the user to create a new AzureMachineTemplate instead + point to the doc above in the error message.

How: add a validation webhook to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/api/v1alpha4/azuremachinetemplate_webhook.go and reject all updates to AzureMachineTemplates.

See https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/api/v1alpha4/azurecluster_webhook.go#L40 for an example.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by devigned** [comment]
There were discussions about merging the `AzureMachineTemplate` and [`AzureMachineTemplate` used in MachinePool](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d5124be8c5a5ca3fc0d7aeb977222b4a59387ef6/exp/api/v1alpha4/azuremachinepool_types.go#L29) via #812. By making the `AzureMachineTemplate` immutable, these types will not be able to be merged since `AzureMachinePool` relies on changes to the template to update the underlying VMSS model.

This observation should not deter making the `AzureMachineTemplate` immutable. Though, it may inform us on how to possibly rename the MachinePool version of the [`AzureMachineTemplate` used in MachinePool](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d5124be8c5a5ca3fc0d7aeb977222b4a59387ef6/exp/api/v1alpha4/azuremachinepool_types.go#L29).

**Comment by shysank** [comment]
I had to do a similar thing for node outbound load balancer spec, and it was painful with a lot of repeated code. Should we try to do something similar to what's done in [kcp webhook](https://github.com/kubernetes-sigs/cluster-api/blob/3de1188f06026d59e733ec1a1bce946732986c75/controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go#L117)?
