### ISSUE TITLE
Local Manager Image Build Process Broken

### ISSUE THREAD

**Issue by alanmeadows** [kubernetes-sigs/cluster-api-provider-azure#127]
/kind bug

**What steps did you take and what happened:**

Follow the documentation to push custom builds of ./manager.

**What did you expect to happen:**

A successful container image can be built and pushed.

**Anything else you would like to add:**

A few issues.  This is somewhat important given quay.io/k8s is somewhat unstable, and most of the time, the images referenced in the components yaml do not exist or are broken or have broken cloud-init setup steps for kubeadm.  I'd like to build and push my own images to work around these issues and contribute fixes.

1) The override variables to point the bazel docker build and push process to a remote repository does not work properly.  The documentation says to do the following:

```bash
# Build the image.
PREFIX=quay.io/k8s \
NAME=cluster-api-azure-controller \
TAG=0.2.0-alpha.4 \
make docker-build

# Push the image.
PREFIX=quay.io/k8s \
NAME=cluster-api-azure-controller \
TAG=0.2.0-alpha.4 \
make docker-push
```

In reality, I had to:

```bash
export STABLE_DOCKER_REPO=gcr.io/cluster-api-azure-controller
export MANAGER_IMAGE_NAME=cluster-api-azure-controller
export MANAGER_IMAGE_TAG=v1.0
export DEV_DOCKER_REPO=gcr.io/cluster-api-azure-controller
make docker-build
```
2) For those unfamiliar with bazel, the [azure-plugin] documentation leads one to believe they can publish to quay.io with the latest version of Bazel.  In reality, publishing doesn't work because of lack of schema v2 support (see https://github.com/bazelbuild/rules_docker/issues/102), thus the pivot to gcr.io above.

3) The build image using `make docker-build` and `make docker-push` results in an image that lacks deployment-template.json:

```bash
$ sudo docker run --rm --entrypoint=/bin/sh -it gcr.io/cluster-api-azure-controller/cluster-api-azure-controller@sha256:a04921e530811ae5dc5021992c4640d19c8e4b53bf56de2e685048653d517c6d 
/app/cmd/manager/manager-amd64.binary.runfiles/__main__ # ls
cmd       external
/app/cmd/manager/manager-amd64.binary.runfiles/__main__ # cd /
/ # find . -name deployment-template.json
/ # find . -name manager
./app/cmd/manager
./app/cmd/manager/manager-amd64.binary.runfiles/__main__/cmd/manager
/ # exit
```
4) The `Dockerfile` (as opposed to the Bazel process) works fine. For those reading this wondering how they might work around these issues, the build process removing the heft and weight and brokeness of Bazel is as simple as the following.  I recommend either fixing `docker-build/docker-push` or simply removing them and offering instructions like the below:

```bash
make manager
docker build -t gcr.io/cluster-api-azure-controller:v1.0 .
docker push gcr.io/cluster-api-azure-controller:v1.0
```

**Environment:**

- cluster-api-provider-azure version: commit 7f482be1078f6836d8e59d4d4aa7622b4ee5ade5 / Feb 13
- Kubernetes version: (use `kubectl version`): 1.13.4
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04
- Bazel:
INFO: Invocation ID: df2e00cc-bad4-4a96-9ad0-75397556659b
Build label: 0.22.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 28 12:58:08 2019 (1548680288)
Build timestamp: 1548680288
Build timestamp as int: 1548680288

**Comment by justaugustus** [comment]
@alanmeadows -- Thank you for filing such a detailed bug report and for wanting to contribute! :)

Hopefully I can address a few of these concerns while the repo is in flux...
- Pushes to `quay.io/k8s/cluster-api-azure-controller` are restricted to project maintainers. You're likely running into some issues because you're trying to push to a registry you don't have access to.
  
  Additionally, there was a recent issue with the Quay production database (yesterday: http://status.quay.io/), which would've impacted reliability for you:
  ```
  Investigating an issue with our production database
  Resolved - The problem appears to be resolved and systems are functioning normally again. We're 
  currently investigating what caused the database to hard lock. 
  Mar 7, 15:44 EST
  Monitoring - We've restarted the database and are currently monitoring the service. 
  Mar 7, 15:39 EST
  Investigating - We're currently investigating an issue with our production database 
  Mar 7, 15:14 EST
  ```

  The k8s-infra-team is working on providing repositories for subprojects and we will plan to move production images there once that happens. Issues to track are https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/118, https://github.com/kubernetes/k8s.io/issues/158
- There have been several improvements since `v0.1.0-alpha.3`. If you're going to be actively developing on capz, I'd suggest building from `master`. The example yamls and kubeadm config are up to date there.
- You're correct that the docs are a little out-of-date. It's a high-priority issue for me and I intend to have an update on them next week. Here's the issue to track: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/98

  In the meantime, I've been using the following to build new images and test deployment:

  ```
  MANAGER_IMAGE_TAG=<your-tag> make docker-build
  MANAGER_IMAGE_TAG=<your-tag> make docker-push

  export AZURE_SUBSCRIPTION_ID="<subscription-id>"
  export AZURE_TENANT_ID="<tenant-id>"
  export AZURE_CLIENT_ID="<client-id>"
  export AZURE_CLIENT_SECRET="<client-secret>"

  make clean

  MANAGER_IMAGE="<your-registry>:<your-tag>" RESOURCE_GROUP="<resource-group>" CLUSTER_NAME="<cluster-name>" time make examples

  DEV_MANAGER_IMAGE="<your-registry>:<your-tag>" RESOURCE_GROUP="<resource-group>" CLUSTER_NAME="<cluster-name>" time make manifests-dev

  make kind-reset

  time clusterctl create cluster -v 10 \
  --provider azure \
  --bootstrap-type kind \
  -m ./cmd/clusterctl/examples/azure/out/machines.yaml \
  -c ./cmd/clusterctl/examples/azure/out/cluster.yaml \
  -p ./cmd/clusterctl/examples/azure/out/provider-components.yaml \
  -a ./cmd/clusterctl/examples/azure/out/addons.yaml
  ```

  For the `make docker-build` and `make docker-push` targets, you'll likely want to use `MANAGER_IMAGE=<registry>:<tag>` instead.
- I _think_ Quay should support v2. The issue that you referenced is fairly old at this point. Tagging @jzelinskie for any details. I have plans to investigate moving image builds into bazel, but it's low priority right now as the Dockerfile works fine (as you mentioned). The Docker make targets in `master` use the Dockerfile, instead of bazel (as I ran into the same issue here as well).
- The missing deployment template is fixed in `master`.


One ask for you...
Would you be fine with changing your GCR registry to use a project e.g., `gcr.io/<project>/cluster-api-azure-controller`, instead of `gcr.io/cluster-api-azure-controller`?

I can see your registry causing confusion for other users once we move the project into GCR.

Thanks again for submitting this!

**Comment by jzelinskie** [comment]
>I think Quay should support v2.

It's being rolled out in waves. I'll whitelist your user.

**Comment by justaugustus** [comment]
Thanks Jimmy!
