### ISSUE TITLE
AzureManagedCluster is useless; let's remove it (and keep AzureManagedControlPlane)

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#1396]
/kind cleanup

**Describe the solution you'd like**
Eliminate AzureManagedCluster. It has absolutely no useful spec or status. We should simply point CAPI Clusters to AzureManagedControlPlane as the InfrastructureRef.

**Comment by alexeldeib** [comment]
we might be able to make this backward compatible by looking for CAPI clusters where InfrastructureRef is currently AzureManagedCluster, and setting InfrastructureRef = ControlPlaneRef

**Comment by alexeldeib** [comment]
wonder what the best practice is for operators automatically cleaning up their own crds, since we kubectl apply them and don't programmatically apply them.

**Comment by CecileRobertMichon** [comment]
/remove-lifecycle rotten
@alexeldeib we should do this pretty soon if we want to remove the experimental label

**Comment by CecileRobertMichon** [comment]
After a discussion around ClusterClass support for managed clusters (special meeting on March 1st https://docs.google.com/document/d/1ushaVqAKYnZ2VN_aa3GyKlS4kEd6bSug13xaXOakAQI/edit#) and how it needs the infraRef in order to satisfy the contract, we might not want to do this after all. CAPA is considering re-introducing AWSManagedCluster to solve the issue (https://github.com/kubernetes-sigs/cluster-api/issues/6126).

cc @alexeldeib @jackfrancis @zmalik

**Comment by CecileRobertMichon** [comment]
won't do

/close
