### ISSUE TITLE
Enforce comments on the codebase

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1443]
Enable linters for enforcing adding a comment to exported methods.

Relevant cluster-api PRs:
kubernetes-sigs/cluster-api#4631
kubernetes-sigs/cluster-api#4669

/milestone Next
/priority backlog
/good-first-issue
/help

**Comment by mboersma** [comment]
It seems that `golint` in our configuration is already catching missing comments.
 
I see they are enabling some default excludes in CAPI, but AFAICT that's not necessary in CAPZ. I picked a random comment, deleted it, and ran `make lint`:

```shell
% make lint
./hack/lint-latest.sh
/Users/matt/Projects/src/sigs.k8s.io/cluster-api-provider-azure/hack/tools/bin/golangci-lint-v1.38.0 run -v
INFO [config_reader] Config search paths: [./ /Users/matt/Projects/src/sigs.k8s.io/cluster-api-provider-azure /Users/matt/Projects/src/sigs.k8s.io /Users/matt/Projects/src /Users/matt/Projects /Users/matt /Users /] 
INFO [config_reader] Used config file .golangci.yml 
INFO [lintersdb] Active 23 linters: [deadcode errcheck errorlint goconst gocyclo godot gofmt goimports golint gosec gosimple govet ineffassign interfacer misspell nakedret prealloc staticcheck structcheck unconvert unused varcheck whitespace] 
INFO [loader] Go packages loading at mode 575 (compiled_files|files|imports|deps|exports_file|name|types_sizes) took 23.087173721s 
WARN [runner] The linter 'interfacer' is deprecated due to: The repository of the linter has been archived by the owner. 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 74.996022ms 
INFO [linters context/goanalysis] analyzers took 43.053309081s with top 10 stages: buildir: 9.043324162s, buildssa: 4.914725845s, goimports: 2.160099005s, nilness: 2.070683194s, gofmt: 1.401810293s, gosec: 1.260226691s, unconvert: 1.238265275s, misspell: 1.14138834s, golint: 1.106058251s, interfacer: 961.684557ms 
INFO [linters context/goanalysis] analyzers took 7.683209018s with top 10 stages: buildir: 6.776627878s, unused: 357.114344ms, directives: 311.944062ms, isgenerated: 237.522734ms 
INFO [runner/skip dirs] Skipped 4 issues from dir azure/services/scalesetvms/mock_scalesetvms by pattern mock* 
...
INFO [runner] linters took 1m21.745326746s with stages: goanalysis_metalinter: 1m11.861483835s, unused: 9.862698242s 
controllers/azurecluster_controller.go:78:1: exported method `AzureClusterReconciler.SetupWithManager` should have comment or be unexported (golint)
func (r *AzureClusterReconciler) SetupWithManager(ctx context.Context, mgr ctrl.Manager, options controller.Options) error {
^
INFO File cache stats: 195 entries of total size 1.5MiB 
INFO Memory: 1050 samples, avg is 286.6MB, max is 1075.7MB 
INFO Execution took 1m44.926293831s               
make: *** [lint] Error 
```

**Comment by KamalSinghKhanna** [comment]
Hi I am new here and work on this issue please guide me how to start.

**Comment by devigned** [comment]
@KamalSinghKhanna, this issue seems to be in question. That is, https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1443#issuecomment-862751690 states that the linter does catch missing comments. This asks to enhance the project to enable the linter to fail when missing comments. The enhancement may not be needed if it is already enabled as stated in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1443#issuecomment-862751690.

I think the work item here would be to:
1) open a PR with a missing comment
2) verify the PR does or doesn't fail due to a missing comment on an exported API
3) link the results into the PR
4) if the linter failed when the comment is missing, then close the issue and link the PR results.
5) if the linter passed when the comment is missing, then change the linter configuration to fail if there are missing comments on exported APIs

If you need more help when it comes to `5`, ping back and we'll point you in the right direction. If you would like to take this issue, please assign yourself. To see how to do that, just run /help.

**Comment by KamalSinghKhanna** [comment]
If I am not wrong, So in this issue i have to add a new public (UpperCase in Go) type or function with missing comment.
Is that right?

**Comment by devigned** [comment]
That should work.

You could do something simpler. You could delete a comment from an exported (public) function.

**Comment by sayantani11** [comment]
@devigned The linter fails as it was expected to. So I guess the issue can be closed.

**Comment by sayantani11** [comment]
The Go-Linter fails when comments are missing as it should.
Verified via #1659

**Comment by CecileRobertMichon** [comment]
thanks @sayantani11!
