### ISSUE TITLE
azurejson controller doesn't have access to ClientID/Secret/TenantID when using AzureClusterIdentity

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1517]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:** The azure.json controller doesn’t have access to the Client secret/id/tenant ID when using AzureClusterIdentity and the manager creds aren’t set. This causes the azurejson secrets to be generated without aadClientID and aadClientSecret set, when not using managed identity, which causes cloud provider to fail (kube-controller-manager goes into crashloop).

Workaround is to keep setting manager credentials (base 64 encoded env vars), or to use managed identity.

Potential fixes to consider (just spitballing):

- Find a way to give access to the creds in the controller through aad-pod-identity
- create an identity for the machine (?)
- make managed system identity default and require env vars for SP cloud provider identity *but this requires the AzureClusterIdentity SP to have Owner access*
- ???

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nader-ziada** [comment]
The json_controller is already reading the `azure_cluster`, so would it make sense to get the controller to also `get` the `AzureClusterIdentity` so it has access to the needed fields?

**Comment by devigned** [comment]
Should we assume the identity on the machines, control plane and workload vms, is the same identity used to provision the infrastructure?

**Comment by nader-ziada** [comment]
I think that would be a fair assumption that everything in the AzureCluster would use the same identity referenced by the AzureCluster unless it was a system assigned or user assigned which already takes precedence

**Comment by CecileRobertMichon** [comment]
> Should we assume the identity on the machines, control plane and workload vms, is the same identity used to provision the infrastructure?

no, but the convenient auto-generated json should (and already did previously). For those requiring a distinct identity (that uses a SP), they currently need to pre-create the azurejson secret.

**Comment by devigned** [comment]
What happens if a user sets both the IdentityRef on the AzureCluster and the VMIdentity and UserAssignedIdentity on the AzureMachineSpec?
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/92c88f2a884a476306a7ddaf66ef087d8e9d0e23/api/v1alpha4/azuremachine_types.go#L52-L66

Perhaps the following rules should be used:
1) If the `AzureMachineSpec` has a User Assigned Identity provided, the machine will use that for the azure.json. (working today)
2) If the `AzureMachineSpec` has a System Assigned Identity specified, the machine will use that System Assigned Identity and the `AzureCluster.Spec.IdentityRef` will be used to assign the resource group contributor role to that System Assigned Identity.
3) If the `AzureMachineSpec` has no identity provided, then it will use the IdentityRef of the `AzureCluster.Spec.IdentityRef` with the implication that the identity, if it is a service principal, will be written to disk.

If we proceed down this path, I would request that we add warnings and events for `3` because it creates a less secure approach to identity usage / management for the cluster.

Thoughts?

**Comment by devigned** [comment]
We might also consider creating a specialized Azure RBAC role with the minimum rights required to achieve the goals of the different roles in the system: 
1) cluster infrastructure provisioning / role assignment identity (`AzureCluster.Spec.IdentityRef`)
2) control plane node / cloud provider identity
3) workload node identity

**Comment by nader-ziada** [comment]
> If we proceed down this path, I would request that we add warnings and events for `3` because it creates a less secure approach to identity usage / management for the cluster.
> 
> Thoughts?

I think that approach makes sense to me, and as for 3, doesn't the secret have to be part of the azure.json? are there any other options there?

**Comment by devigned** [comment]
The azure.json can use an User Assigned Identity, System Assigned Identity or a Service Principal. Only the Service Principal requires the secret to be in the azure.json. The other two use IMDS on the VM to request the JWT.

**Comment by CecileRobertMichon** [comment]
> We might also consider creating a specialized Azure RBAC role with the minimum rights required to achieve the goals of the different roles in the system:

#1317 covers this
