### ISSUE TITLE
Azure managed cluster created using a existing VNet on deletion deletes the existing VNet

### ISSUE THREAD

**Issue by LochanRn** [kubernetes-sigs/cluster-api-provider-azure#1590]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Created azure managed cluster using capz with an existing VNet. While deleting the cluster even the VNet is deleted. 

**What did you expect to happen:**
The cluster has to be deleted successfully but the VNet has to remain as it is not managed by capz.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Although both azure cluster and azure managed clusters use virtualnetwork service the difference in api's is creating this issue.  

VNet Spec in AzureCluster : 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/eced64af3f168b8e76dfb16c76c221bf079c7f29/api/v1alpha4/types.go#L78-L96

VNet Spec in AzureMannagedCluster
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/eced64af3f168b8e76dfb16c76c221bf079c7f29/exp/api/v1alpha4/azuremanagedcontrolplane_types.go#L89-L93

In the below snippet we check for the ID field, if it is empty it shows it is managed by capz. 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/eced64af3f168b8e76dfb16c76c221bf079c7f29/api/v1alpha4/types.go#L99-L101

For Azure managed clusters this field will always be empty during deletion. Because the ID is not a Spec In the ManagedCluster VNet the ID is not persisted anywhere. So even though a patch is done in the azuremanagedcontrolplane reconciler the ID is omitted. 

The same issue exists for Subnets as well. 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by LochanRn** [comment]
Ideal way to fix this issue would be update the Managed VNet and Managed Subnet Spec to a similar form as that of Azure Clusters. 

A must needed change is to add an ID field. 

Should we add Tags and Resource Group as well ?

**Comment by LochanRn** [comment]
cc @alexeldeib @nprokopic @CecileRobertMichon .

**Comment by LochanRn** [comment]
I found this issue when I was coming up with scenarios for e2e tests 😅

**Comment by LochanRn** [comment]
I think we need to replace 
```
 type ManagedControlPlaneVirtualNetwork struct { 
 	Name      string                    `json:"name"` 
 	CIDRBlock string                    `json:"cidrBlock"` 
 	Subnet    ManagedControlPlaneSubnet `json:"subnet,omitempty"` 
 }
``` 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7f6a9ca8df9190ae35ac49a259cdf0d23c0bc776/azure/scope/managedcontrolplane.go#L183-L189

with this

```
 type ManagedControlPlaneVirtualNetwork struct { 
        infrav1.VnetSpec `json:",inline"`
 	Subnet    ManagedControlPlaneSubnet `json:"subnet,omitempty"` 
 } 
```

```
// Vnet returns the cluster Vnet.
func (s *ManagedControlPlaneScope) Vnet() *infrav1.VnetSpec {
	return &s.ControlPlane.Spec.VirtualNetwork.VnetSpec
}
```

for the Id to be persisted in amcp.

**Comment by CecileRobertMichon** [comment]
Does AzureManagedControlPlane support BYO vnet?

**Comment by CecileRobertMichon** [comment]
Another idea: we could change the `IsManaged()` func to actually do a GET on the resource and check the actual owner tags similar to what we do for the RG:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/azure/services/groups/groups.go#L121

The reason I bring this up is that I've been looking at changing how we do GETs on existing resources to make it more consistent as part of #1541

**Comment by LochanRn** [comment]
> Does AzureManagedControlPlane support BYO vnet?

Yes it does provide options to configure your own VNet.

**Comment by LochanRn** [comment]
> Another idea: we could change the `IsManaged()` func to actually do a GET on the resource and check the actual owner tags similar to what we do for the RG:
> 
> https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/azure/services/groups/groups.go#L121
> 
> The reason I bring this up is that I've been looking at changing how we do GETs on existing resources to make it more consistent as part of #1541

Yup you are right 👍 I could just make a call to this function to check if it exists or not in deletion function. https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7f1796c14e85a6f391b56bed6fd1e491f455d1ea/azure/services/virtualnetworks/virtualnetworks.go#L137 

I did realise this as well while debugging.  But ...

I found a tradeoff in the two methods of solving this issue : 
getExisting/IsManaged method is also used in the Reconcile. This means we are making a get call to the azure api on every reconcile. This essentially because we are not persisting the Id. 

On the other hand to persisting the Id it would be a breaking change.

I thought the 2nd was more efficient although it would be a breaking change.

**Comment by LochanRn** [comment]
ok regardless Id exists or not it does make a call to the azure api. I will probably use the getExisting function to fix this issue. This will not have any api changes :)

**Comment by nprokopic** [comment]
Thanks @LochanRn for bringing this up.

Another issue with the current `AzureManagedControlPlaneSpec.VirtualNetwork` field is that it is a "global" cluster field, it gets applied to all node pools.

On the other hand, in Azure, this part of the network spec belongs to [ManagedClusterAgentPoolProfile](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update#managedclusteragentpoolprofile), so it is configurable per node pool.

Virtual network is not even part of cluster-wide [ContainerServiceNetworkProfile](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update#containerservicenetworkprofile).

WDYT about aligning CAPZ managed cluster network spec with this and adding `vnetSubnetID` and `podSubnetID` (from Azure's `ManagedClusterAgentPoolProfile`) to `AzureManagedMachinePoolSpec` as optional fields?
- Using these fields would inject node pools into existing subnets.
  - This would be a different VNet than the one that is created by default now, so it would not be deleted by the current delete implementation.
  - When these fields are specified we do not delete the subnet (we can assume it's created independently from the managed cluster itself).
- For node pools that do not have these fields set, the current cluster-wide behavior would be used.
  - Same VNet/subnet would be created like now.
  - That VNet/subnet created by default would be then also deleted.

Here's the spec from Azure for these fields:

| field | type | description |
| --- | --- | --- |
| vnetSubnetID | string | The ID of the subnet which agent pool nodes and optionally pods will join on startup.<br>If this is not specified, a VNET and subnet will be generated and used. If no podSubnetID is specified, this applies to nodes and pods, otherwise it applies to just nodes. This is of the form: `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworks/{virtualNetworkName}/subnets/{subnetName}` |
| podSubnetID | string | The ID of the subnet which pods will join when launched.<br>If omitted, pod IPs are statically assigned on the node subnet (see vnetSubnetID for more details). This is of the form: `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworks/{virtualNetworkName}/subnets/{subnetName}` |

**Comment by nprokopic** [comment]
> WDYT about aligning CAPZ managed cluster network spec with this and adding vnetSubnetID and podSubnetID (from Azure's ManagedClusterAgentPoolProfile) to AzureManagedMachinePoolSpec as optional fields?

These should be basically backward compatible changes. The logic around new optional fields would get activated only when those fields are set.
