### ISSUE TITLE
Support autoscaling on ManagedMachinePool

### ISSUE THREAD

**Issue by felipeweb** [kubernetes-sigs/cluster-api-provider-azure#1669]
/kind feature

**Describe the solution you'd like**
Enable autoscaling from MachinePools and ManagedMachinePool

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
thanks for opening the PR to enable autoscaling for AKS clusters @zmalik!

Going to retitle this issue to reduce scope to managed clusters (which is what the PR does already). For regular MachinePools, we still need https://github.com/kubernetes-sigs/cluster-api/issues/4063 to be done in order to support cluster-autoscaler. @mboersma is already working on it.

/retitle Support autoscaling on ManagedMachinePool

**Comment by CecileRobertMichon** [comment]
This is done for managed clusters #1815 

/close
