### ISSUE TITLE
[feature request]enable csi-proxy by default on Windows 1.21+

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/cluster-api-provider-azure#1814]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Azure Disk CSI driver depends on csi-proxy.exe on Windows, we should enable csi-proxy by default on Windows 1.21+
on aks-engine, there is `windowsProfile.enableCSIProxy` to control whether enable csi-proxy on Windows node, and it's fine that we enable csi-proxy on capz Windows node by default.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jsturtevant** [comment]
I propose we do this with 1.22+ with containerd using hostprocess pod to install and configure the proxy.  We can use `ClusterResourceSet` with label matches such as `CSIProxy: true` and `windows: enabled` on the cluster to run a DaemonSet that installs the proxy.

fyi @marosset 

/sig windows

**Comment by CecileRobertMichon** [comment]
@jsturtevant re: using `ClusterResourceSet`, this would be the easier way to do it right now but we should follow whatever gets decided as part of https://github.com/kubernetes-sigs/cluster-api/issues/5491

My concern with using ClusterResourceSets for more and more things is that 1) the templates are going to become huge and 2) it's hard to keep the external components and the k8s versions in sync since the resource sets are "apply once", and as far as I understand there is a pretty tight coupling between the out of tree drivers and k8s versions.

**Comment by andyzhangx** [comment]
1.23 is too late, we are also migrating all other Windows e2e tests to capz (not only WS2022) which should cover 1.19 and above versions. Can we make csi-proxy.exe run by default on all Windows images since csi-proxy is a fundamental component on Windows container?

**Comment by andyzhangx** [comment]
any update? is it possible to run csi-proxy.exe on all Windows nodes? csi-proxy is an essential service on Windows, it's better run this service when Windows node is up, below is the manual way to start up csi-proxy on Windows
```console
> cd c:\k
Invoke-WebRequest https://acs-mirror.azureedge.net/csi-proxy/v1.0.2/binaries/csi-proxy-v1.0.2.tar.gz -OutFile csi-proxy.tar.gz;
tar -xvf csi-proxy.tar.gz
copy .\bin\csi-proxy.exe .
sc.exe create csiproxy binPath= "c:\k\csi-proxy.exe -windows-service -log_file=c:\k\csi-proxy.log -logtostderr=false"
sc.exe failure csiproxy reset= 0 actions= restart/10000
sc.exe start csiproxy
```

**Comment by marosset** [comment]
> any update? is it possible to run csi-proxy.exe on all Windows nodes? csi-proxy is an essential service on Windows, it's better run this service when Windows node is up, below is the manual way to start up csi-proxy on Windows
> 
> ```
> > cd c:\k
> Invoke-WebRequest https://acs-mirror.azureedge.net/csi-proxy/v1.0.2/binaries/csi-proxy-v1.0.2.tar.gz -OutFile csi-proxy.tar.gz;
> tar -xvf csi-proxy.tar.gz
> copy .\bin\csi-proxy.exe .
> sc.exe create csiproxy binPath= "c:\k\csi-proxy.exe -windows-service -log_file=c:\k\csi-proxy.log -logtostderr=false"
> sc.exe failure csiproxy reset= 0 actions= restart/10000
> sc.exe start csiproxy
> ```

@jsturtevant should we run csi-proxy as a windows service or as a daemonset?
If we want to run it as a daemonset it sounds like we can host the container images in sig-windows-tool for now since it sounds like the csi-proxy project doesn't want to maintain csi-proxy running in a hostprocess container.
Instead they'd like to get the individual csi plugin drivers able to run as host-process containers?
https://github.com/kubernetes-csi/csi-proxy/pull/179

**Comment by andyzhangx** [comment]
@marosset I think run csi-proxy as a daemonset is too heavy load and cause dependency on hostprocess feature which is still alpha on 1.23, just run csi-proxy as a windows service when Windows node is up, that's simple enough. And when hostprocess feature is beta, we could provide an alternative solution to deploy csi-proxy on Windows node using host-process.

**Comment by marosset** [comment]
> @marosset I think run csi-proxy as a daemonset is too heavy load and cause dependency on hostprocess feature which is still alpha on 1.23, just run csi-proxy as a windows service when Windows node is up, that's simple enough. And when hostprocess feature is beta, we could provide an alternative solution to deploy csi-proxy on Windows node using host-process.

hostprocess containers is beta for 1.23 :)

**Comment by jsturtevant** [comment]
This was resolved for ci templates with https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2012
