### ISSUE TITLE
Hardcoded CIDR blocks in Calico CNI config

### ISSUE THREAD

**Issue by awesomenix** [kubernetes-sigs/cluster-api-provider-azure#183]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Calico CNI has hardcoded pod CIDR blocks to `192.168.0.0/16`, plan to make it configurable,

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

PR: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/181

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@awesomenix @juan-lee is this still relevant? Can I pick it up? any pointers?

**Comment by awesomenix** [comment]
Seems like this was recently switched to calico using vxlan, but the pod cidr is still hardcoded https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/9b553da079817f83fe7659696d5a88b60724463d/cmd/clusterctl/examples/azure/addons.yaml#L605 , making this cidr match the input network pod cidr would be desirable

**Comment by justaugustus** [comment]
Pod CIDRs are hardcoded because these manifests are grabbed directly from Project Calico.
The reason this was on the backburner is because we currently assume `192.168.0.0/16` is the pod CIDR block across the board.

If we're going to change it here, we need to make sure it's parameterized and configurable everywhere in the repo, not just in addons.yaml.
