### ISSUE TITLE
deleting AzureManagedMachinePool before AzureManagedControlPlane is fully initialized causes resource leakage

### ISSUE THREAD

**Issue by dantiandb** [kubernetes-sigs/cluster-api-provider-azure#1875]
/kind bug

**What steps did you take and what happened:**
Create an AKS cluster with CAPI/CAPZ. Specifically CRs created:

- Cluster CR (CAPI)
- AzureManagedClusterCR (CAPZ)
- AzureManagedControlPlane CR (CAPZ)
- AzureClusterIdentity CR (CAPZ)
- MachinePool CR (CAPI) / AzureManagedMachinePool CR (CAPZ) -> one system pool and one worker pool

Once the CRs were submitted to the K8s cluster, watched in Azure Portal for the created resource group and AKS cluster to appear.

Waited until I saw the machine pools enter "Creating" state within the AKS cluster in Azure Portal.

Deleted the worker pool CR (MachinePool + AMMP(AzureManagedMachinePool)).

The worker pool continued to create and enter succeeded state as seen in Azure Portal. The worker pool continues to persist and function normally as if the worker pool CRs (Machine Pool + AMMP) were still existing in K8s.

**What did you expect to happen:**
When the worker pool CRs are deleted (MachinePool + AMMP), the actual machine pool resource backing them should also be cleaned up eventually.

**Anything else you would like to add:**
I think the root cause behind this problem is a race condition where the MachinePool + AMMP CRs are deleted before the AzureManagedControlPlane is fully initialized.

I noticed the AMMP CR deleted immediately so it never had a finalizer added to it as this part in the reconciliation would do:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/exp/controllers/azuremanagedmachinepool_controller.go#L238

Checking controller logs, seems like the AMMP was still waiting for the control plane to fully initialize here:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/exp/controllers/azuremanagedmachinepool_controller.go#L197

Looking at the control plane reconciliation it appears it's actually responsible for initially creating the machine pools (not the AMMP reconciler) as evidenced here:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/exp/controllers/azuremanagedcontrolplane_reconciler.go#L79
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/managedclusters/managedclusters.go#L170

So since the delete happens **after** the control plane initially creates the machine pools but **before** the finalizer gets added to them it will cause the resources to leak. 

**Environment:**

- cluster-api-provider-azure version: 
  v1.0.0
- Kubernetes version: (use `kubectl version`): 
  v1.21.2
- OS (e.g. from `/etc/os-release`): 
  Ubuntu 18.04.5 LTS

**Comment by alexeldeib** [comment]
Hmmm. We could solve this a couple ways.

AMCP could handle scale down of non existing pools. that would mean calling AP API though, since I don’t think you can mutate pools after creation using MC API.

Or we could use status to track stats of resources and make sure we clean them up appropriately. Still needs to be done in AMCP due to race.

Or we could ensure AMMP/MP have deletion finalizers applied immediately to block deletion. That *might* still leave room for a race between adding the finalizer and deleting the pool. It might be that we want to add it via mutating webhook to avoid that race?

I’d lean option 2, feels more resilient, but not sure about the race between initial create/delete and applying the webhook.
