### ISSUE TITLE
Add CodeQL workflow to Github to check security vulnerabilities

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1961]
CodeQL is an opensource tool that saves the codebase to a database and by making queries to it find possible vulnerabilities, bad patterns in the code.

https://codeql.github.com/

/area security

Related CAPA issue: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3064

**Comment by shysank** [comment]
cc @CecileRobertMichon Afaik we don't have much automation around code security scanning, thought this would be a good start since capa has already done it. wdyt?

**Comment by CecileRobertMichon** [comment]
sure, let's try it out and see what info we get out of it

I personally haven't experimented with CodeQL before so I don't have any strong opinions here. Related to security (but different because it's for the created k8s clusters), @mboersma opened #1793

**Comment by mboersma** [comment]
I've used CodeQL in a GH action, but for a [python project](https://github.com/Azure/azure-capi-cli-extension/actions/workflows/codeql-analysis.yml). 👍🏻 We should try it here.

The [kubescape](https://github.com/armosec/kubescape) tool is somewhat similar, in that it looks for possible vulnerabilities in the definitions of k8s resources (you can also point it at a set of .yaml files rather than a running cluster).
