### ISSUE TITLE
Handle `TerminalErrors` in the AzureCluster controller

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api-provider-azure#1973]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Currently, the AzureMachine controller handles both transient and terminal errors, but the AzureCluster controller only handles transient errors. By adding support for terminal errors, we can return terminal errors in Reconcile() for services like subnets.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
I'm going to mark this as bug because it's a miss that it doesn't handle terminal errors

/kind bug
/good-first-issue

More details for first time contributors:

The AzureMachine controller code can be used as an example of how to handle termnial reconcile errors:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/controllers/azuremachine_controller.go#L306-L314

The ask is to do the same for AzureCluster reconcile errors in https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/controllers/azurecluster_controller.go#L223

**Comment by sayantani11** [comment]
Can I take this?
But guess will require some help
