### ISSUE TITLE
add support for custom-headers for AKS 

### ISSUE THREAD

**Issue by zmalik** [kubernetes-sigs/cluster-api-provider-azure#1981]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
add support for custom-headers for AKS. 
Custom headers are used by Azure API to enable several features for AKS controlplane and AKS nodepools, few examples would be:

For control-plane:
```
- Enable Container Storage Interface (CSI) drivers for Azure disks and Azure Files 
```

For nodepools:
```
- Adding a node pool for GPU nodes
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by NovemberZulu** [comment]
Since this is general custom headers feature, there are two points I'd like to confirm:

1.  There is no easy way to actually check if headers were set on an Azure object or not, is there? If my understanding is correct, we can't detect drift on custom headers, so it is not 100% reconcile flow.

2.  What CRDs should contain custom header field?

Thanks!

**Comment by zmalik** [comment]
> There is no easy way to actually check if headers were set on an Azure object or not, is there? If my understanding is correct, we can't detect drift on custom headers, so it is not 100% reconcile flow.

Right, this will be just added to the HTTP API request.

> What CRDs should contain custom header field?

IMO control-plane custom headers should go to `AzureManagedControlPlaneSpec`. Nodepool related headers should live in `AzureManagedMachinePool`
