### ISSUE TITLE
Support "managed" semantics for an existing private DNS zone

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-provider-azure#1983]
/kind feature

**Describe the solution you'd like**
I have to use an existing private DNS zone. I am not authorized to delete the zone, but only to manage vnet links and records in the zone. I want CAPZ to manage the vnet link and records in this zone. When CAPZ deletes the cluster, I want it to only delete the records and vnet link it created, and to not delete the zone itself.

**Anything else you would like to add:**
CAPZ [sees a private DNS zone as either "managed" or "unmanaged."](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d0605831a48a551f1292b21c1c6a3a1bdbec8fc5/azure/services/privatedns/privatedns.go#L53-L154) If the zone is "managed," then CAPZ
- manages a vnet link in the zone
- manages the records in the zone
- deletes the zone when it deletes the cluster

However, if I configure CAPZ to use an existing private DNS zone, then CAPZ will treat is as "unmanaged," by default. Afterward, I can add a tag to the private DNS zone, and CAPZ will treat it as "managed." However, CAPZ [deletes a "managed" zone](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d0605831a48a551f1292b21c1c6a3a1bdbec8fc5/azure/services/privatedns/privatedns.go#L188-L194) when it deletes the cluster.

**Environment:**

- cluster-api-provider-azure version: v1.1.0
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@dlipovetsky this seems to be a bug. We shouldn't return [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d0605831a48a551f1292b21c1c6a3a1bdbec8fc5/azure/services/privatedns/privatedns.go#L74) when the private zone is unmanaged, just skip creating/updating the zone, since the management of vnet links is separate.

Also, that log message about tagging the zone manually is misleading, it should only apply to DNS zones that were created with previous versions of CAPZ, before tags were being applied.

**Comment by shysank** [comment]
/close
closing this as this addressed by https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2007
