### ISSUE TITLE
Use controller-runtime setup-envtest instead of fetch_ext_bins.sh

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-azure#1990]
/kind feature

Hey folks,

just wanted to make you aware of that there is a tool by controller-runtime which can be used to setup the controller-runtime envtest binaries (https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest).

It's already used in core CAPI: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L437-L441

I think this could be a good first issue, if you want to adopt setup-envtest.

**Environment:**

- cluster-api-provider-azure version: latest
- Kubernetes version: (use `kubectl version`): -
- OS (e.g. from `/etc/os-release`): -

**Comment by CecileRobertMichon** [comment]
/good-first-issue

Ask is to use `setup-envtest` from controller-runtime instead of fetch_ext_bins.sh, just like https://github.com/kubernetes-sigs/cluster-api/commit/77f62724adb45ed039c6a759b65d09734ad3e4d8 did it for CAPI.

This will require:
1) adding the setup-envtest install to the makefile like https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L728
2) deleting the fetch_ext_bins.sh script
3) adding a KUBEBUILDER_ASSETS var https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L438
4) using KUBEBUILDER_ASSETS in the makefile go-test and test-cover targets, and removing the KUBE_APISERVER and ETCD targets

To test your change is working properly, you should be able to run `make test` locally without errors.

**Comment by sbueringer** [comment]
I think once the test targets are using setup-envtest (the way it's done in core CAPI), this target can be deleted.

But let's wait for feedback from Cecile as I'm not really familiar with CAPZ.

**Comment by CecileRobertMichon** [comment]
> I think once the test targets are using setup-envtest (the way it's done in core CAPI), this target can be deleted.

+1

**Comment by CecileRobertMichon** [comment]
/remove-lifecycle stale
/unassign @Darshnadas

Please feel free to reassign if you pick this up again
