### ISSUE TITLE
Support KUBERNETES_VERSION without "v" for Windows

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#2333]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
`KUBERNETES_VERSION` supports both versions like "1.21.5" and "v1.21.5" for Linux clusters. However, I found that if I set it without "v", Windows kube-proxy Pod creation would fail, complaining about failing to pull `sigwindowstools/kube-proxy:1.23.5-calico-hostprocess`. `sigwindowstools/kube-proxy:1.23.5-calico-hostprocess` should be ``sigwindowstools/kube-proxy:v1.23.5-calico-hostprocess``.

**What did you expect to happen:**
Both versions with or without "v" works for Windows. Or only versions with "v" are supported for both Linux and Windows clusters.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
CAPI actually requires all Kubernetes version to have the "v" prefix to match kube semver format. The mutating webhooks default the version fields in the CRDs to add the "v" prefix if it's missing, eg. https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/machine_webhook.go#L64, so that's why you don't notice it failing if you don't add it yourself.

Since the version variable is being directly used in the template for sigwindowstools image tags, one easy fix would be to append the "v" prefix if it's not already there in the templates and/or scripts. Not sure if there's any way to use envsubst to add prefix to an environment variable if it's missing?

**Comment by lzhecheng** [comment]
Closing this issue since it's not a must-have.
