### ISSUE TITLE
Modify NSG IsManaged function to use tag

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cluster-api-provider-azure#2381]
/kind feature

**Describe the solution you'd like**
Modify NSG IsManaged function to utilize "owned" tag

**Anything else you would like to add:**
Dependent on #2367 being closed.

**Comment by CecileRobertMichon** [comment]
@josh-ferrell could you expand a bit on the motivation here? Is it purely code cleanup? Is it to allow BYO NSG without bringing a vnet? 

Things to watch out for will be 
1) How will we know to create the NSG in the first place? for vnets we just create the vnet if it doesn't exist, it never gets updated. For NSGs it's a little different because we update NSGs when updates are needed (eg. a rule is added), so we can't simply skip create/update if it already exist. Right now it relies on the fact that if the vnet is owned by CAPZ, then so is the NSG.
2) How to ensure backcompat. We can't simply assume that all NSGs that don't have a tag are not managed since they may have been created by a previous version of CAPZ that wasn't creating the tag yet.

**Comment by CecileRobertMichon** [comment]
It's a valid use case, although so far we decided to stay away from it in CAPZ because as soon as CAPZ manages subnets/NSGs/route tables but not the VNet, it means it needs to make PUT calls to a resource it didn't create and doesn't own, since the subnets are a nested resource of the VNet. This is dangerous as it could cause race conditions if something else is updating the VNet at the same time, and we might overwrite some changes made by their LAN/WAN team. In general, the implicit rule we've adopted is "CAPZ only touches the resources it owns". We can revisit but need to be very careful about the implications of modifying a VNet that is being managed elsewhere.

Do you have real user scenario for this or is it hypothetical at this point?
