### ISSUE TITLE
provide e2e test for ACR image pulling 

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/cluster-api-provider-azure#2403]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We already have in-tree credential provider and will have out of tree credential provider, so we should have e2e test for both scenarios.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

/kind test

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by andyzhangx** [comment]
cc @lzhecheng

**Comment by lzhecheng** [comment]
There will be 3 steps to complete the task:

- [ ] Create a capz cluster with oot kubelet credential provider (linux, windows)
- [ ] Deploy such cluster with a test-infra job
- [ ] Verify it works with e2e test code

For the first step, I have verified locally that the [cluster template](https://github.com/lzhecheng/cloud-provider-azure/blob/eaa7138f86f4e39fba828d4973a2b9af8a12865f/tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml) will work for linux worker node. It curls credential provider binary and `credential-provider-config.yaml` file in kubeadm script. Also it puts kubelet args like `feature-gates` into `kubeletExtraArgs`.
I can put the template in cloud-provider-azure repo for now but I believe it will be moved to capz repo since the oot is in the roadmap.

For the second step, I am working on capz script. The new script will build kubelet credential provider, just like CCM and CNM images, push them to az storage blob. The behavior will be controlled by an environment variable: `TEST_ACR_CREDENTIAL_PROVIDER`.

For the third step, I will create a cloudproviderazure ACR (anonymous pull disabled) to hold a hello-world image. The e2e test will simply apply a DaemonSet to ensure the image can be pulled on all worked node (linux and windows).

**Comment by lzhecheng** [comment]
/close
Pipeline here: https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-master-credential-provider-capz
