### ISSUE TITLE
Webhook validation for failureDomain zone availability 

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api-provider-azure#2470]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
CAPZ already supports creating Machines in specific `failureDomains`, [however not all locations in Azure have multiple AZs](https://docs.microsoft.com/en-us/azure/availability-zones/az-overview#azure-regions-with-availability-zones).
For example setting a `failureDomain` in `westus`, the Machine is never created with the below error:
```
      message: 'virtualmachine failed to create or update. err: failed to create resource
        my-azure-zone/my-azure-zone-md-0-klvrs (service: virtualmachine):
        compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400
        -- Original Error: Code="LocationNotSupportAvailabilityZones" Message="The
        resource ''Microsoft.Compute/virtualMachines/my-azure-zone-md-0-klvrs''
        does not support availability zones at location ''westus''."'
```

It would be great if these errors could be bubbled up earlier before the `MachineDeployment` object is created.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
```
v1.3.2
```
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Hi @dkoshkin, thanks for opening this issue! 

Any validation that requires making calls to Azure APIs is tricky to do in webhook validation as 1) it requires credentials / an authorizer 2) making the API calls can take time whereas webhook validation should be very fast for good UX

In this case, we could theoretically maintain a static list of regions and AZ support to use for validation but that wouldn't be great from a maintainability perspective because it would require us to update code to support new zones and new regions. It would be much better if we could check if a certain region/zone was supported dynamically. Going one step further, we could check if the Azure subscription being used has quota for that region/zone (#519).

Let me know if you have any thoughts or suggestions.

**Comment by dkoshkin** [comment]
Thanks for the quick reply @CecileRobertMichon!
>1) it requires credentials / an authorizer 2) making the API calls can take time whereas webhook validation should be very fast for good UX

These are great points.

The error is already pretty visible as a `Machine` event. I will close this but we can discuss further if someone else has similar use-cases.
