### ISSUE TITLE
providerId in lowerCase does not match the providerId on the nodes

### ISSUE THREAD

**Issue by zmalik** [kubernetes-sigs/cluster-api-provider-azure#2533]
/kind bug

**What steps did you take and what happened:**
CAPI does several operations based on providerIds to determine the list of VMs in AKS. I have only tested it with AKS 

example:

providerID format present on the node:
```
azure:///subscriptions/<subscriptionuid>/resourceGroups/rg-node/providers/Microsoft.Compute/virtualMachineScaleSets/aks-shared001-123456-vmss/virtualMachines/1789
```
ProviderID format passed to AMMP and later to MP
```
azure:///subscriptions/<subscriptionuid>/resourcegroups/rg-node/providers/microsoft.compute/virtualmachinescalesets/aks-shared001-123456-vmss/virtualmachines/1789

```

This can cause issues when using full providerID to find nodes. Which we do after the bugfix https://github.com/kubernetes-sigs/cluster-api/pull/6971 
Any solution should also address https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1585 where resource groups were required to be in lower case.

**Comment by CecileRobertMichon** [comment]
Looks like this might actually be caused cloud-provider-azure converting the RG name to lower case:

See: 
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/88c9b89611e7c1fcbd39266928cce8406eb0e728/pkg/provider/azure_standard.go#L537
and https://github.com/kubernetes-sigs/cloud-provider-azure/blob/88c9b89611e7c1fcbd39266928cce8406eb0e728/pkg/provider/azure_vmss.go#L372

cc @juan-lee @alexeldeib 

@feiskyer @nilo19 @lzhecheng does anyone know why cloud-provider-azure isn't preserving the RG name upper cases? This causes a mismatch between actual Azure provider ID and node provider ID.

**Comment by lzhecheng** [comment]
I don't know the background but I feel like ID in lowercase makes things easier? Is there any potential risk to do so?

**Comment by jackfrancis** [comment]
@lzhecheng the key thing here is that the cluster-api and capz set the providerID string (this is essentially the Azure resource reference, e.g.: `"azure://subscriptions/123/resourceGroups/my_resource_group/providers/Microsoft.Compute/virtualMachines/my-vm"`) to match the format enforced by cloud-provider-azure when registering the node.

**Comment by jackfrancis** [comment]
Now that we have merged a fix to @zmalik's issue, I'd like to provide some backstory, and how we plan to ensure this doesn't reoccur.

The quick backstory is that cluster-api has legacy code that evalutes a cloud provider's node reference (i.e., a URI mapping that correlates a Kubernetes node [e.g., [`poo1-00004`] to the underlying infrastructure resource [e.g., `azure:///subscriptions/9107f2fb-e486-a434-a948-52e2929b6f18...`] for equality by using only a portion of the infrastructure resource URI. For example, in the below Azure resource reference URI (also known as the `nodeRef`).

- `azure:///subscriptions/9107f2fb-e486-a434-a948-52e2929b6f18/resourceGroups/MC_rg_capz-managed-aks_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool0-10226072-vmss/virtualMachines/0`

Cluster API wants to evaluate the above for equality by extracting only the "ID" substring (in the above example the "ID" is `0`). The justification for this is because for other cloud providers, the per-VM Set identifier is in fact globally unique. In Azure, however (and possibly other cloud providers), the "ID" above is only unique within the namespace of that particular VM Set (VMSS in Azure). The consequence of that is that in various code flows, where we need to evaluate a provider's node reference for equality (for example, when organizing node references into pools that correlate with the cloud provider's VM Set, or when doing the original work of correlating a Cluster API machine to its underlying cloud provider infrastructure reference, we make the mistake of evaluating the below, discrete VM references as equal:

- `azure:///subscriptions/9107f2fb-e486-a434-a948-52e2929b6f18/resourceGroups/MC_rg_capz-managed-aks_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool0-10226072-vmss/virtualMachines/0`
- `azure:///subscriptions/9107f2fb-e486-a434-a948-52e2929b6f18/resourceGroups/MC_rg_capz-managed-aks_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool3-10226072-vmss/virtualMachines/0`

A close read of the two above examples shows that they are two different VMs (VMSS instances): one in the `aks-agentpool0-10226072-vmss` VMSS, and the other in the `aks-agentpool3-10226072-vmss`. As a result of making that incorrect equality evaluation, side-effects like those that this issue captures are observed. (To be pedantic: the issue described above is not 100% causal w/ respect to the specific issues experienced by @zmalik, but are more precisely classified as 2nd order edge cases resulting from the Cluster API code preferring the "ID" substring as entirely representitive of the node reference.)

The above-described edge case behaviors have been understood for a long time, but the community has thus far been able to agree upon a non-breaking path forward. Original issue:

- https://github.com/kubernetes-sigs/cluster-api/issues/4526

A possible fix (this fix does not address back-compat which is why it hasn't merged):

- https://github.com/kubernetes-sigs/cluster-api/pull/6412

Because the legacy Cluster API code behaviors described in the backstory have existed up until the v1 (v1beta1) release of Cluster API, those behaviors are agreed as being "contractual", and so the community wants to properly address the breaking nature of changing the underlying implementation.

To sum up the backstory: now that we have more concrete evidence that capz customers are in fact suffering the symptoms of these long-existent edge cases, we are prioritizing addressing them, and will drive the process of achieving consensus within the community for how to introduce this "breaking" change.

As to how we addressed @zmalik's specific issues.

@CecileRobertMichon was able to identify a specific code path that could be updated in a non-breaking way to evaluate the entire infra reference URI instead of just Cluster API's understanding of its "ID" property:

- https://github.com/kubernetes-sigs/cluster-api/pull/6971

Unfortunately, the above fix revealed a previously unknown capz-specific bug: the full infrastructure reference string as derived from the Azure APIs is *not* actually the infrastructure reference string that the canonical cloud-provider-azure project (i.e., the standard Kubernetes runtime for running in Azure). When an Azure node is bootstrapped, the cloud-provider-azure runtime actually, purposefully enforces lowercase characters for the resource group substring. With that discovery, we updated capz to conform to the cloud-provider-azure standard:

- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2536

In summary, those two fixes together (one patch to the cluster-api-controller and one patch to the cluster-api-provider-azure-controller) work to overcome @zmalik's issues.

In the near term we are advocating for a quick release of cluster-api 1.2.1 to make the Cluster API fix generally available to Azure customers; after which the capz community will quickly follow with its own patch release to ensure that the larger capz community can operate multiple VMSS-back node pools without running into these issues.

**Comment by NovemberZulu** [comment]
After doing some archeology, I found out the reason for lowercase resource group name: it was introduced kubernetes/kubernetes#74882 in to work around kubernetes/kubernetes#71994 --  resource group name case is not consistent. This _looks_ like an Azure bug to me, tbh, and naturally I have no clue if it was fixed or not.
