### ISSUE TITLE
Evaluate whether Kubescape security scanner is worth keeping

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#2770]
/kind bug

**What steps did you take and what happened:**

We introduced the Kubescape security scanner in #1793. If the aggregate score was worse than a given threshold, the test failed. 

But soon after, the score seemed to fluctuate for reasons that weren't obvious, so we adjusted the threshold so that it couldn't fail, and the test became purely informative.

The goal was still to polish up the test, ensure it is robust to erroneous failures, and reset a useful threshold for failure. The scanner itself has been updated, but stays pinned at a working version.

Until recently, when the pinned version began to fail as well, so we've disabled the security scanner spec entirely in #2768.

The remaining question is only: rehabilitate or remove?

See also #2629, which should be resolved when this is.

**Comment by dtzar** [comment]
I don't see any reference to kubescape being used in CAPI and I can't even see how it would work with existing code still there if you did re-enable it today. 

At any rate, I can generally see value in this running.  However, since we're not maintaining any type of compliance/certification with any flavors of CAPZ I don't think it should be something which blocks PRs.  IMO it should be run with one or maybe two flavors (i.e. Self-managed and/or MangedCluster) and run on a regular basis (i.e. 1x a week) with other jobs and results published to same place such as with Trivy scan results.  If there were a template/flavor specific to CISA/NSA, then it should be PR blocking for that flavor.

All of this said - it assumes that we're not spending an undue amount of time fixing flaky testing with it.. this is hard to know. Using the [GH Action ](https://github.com/kubescape/github-action) should help it be more stable.

**Comment by mboersma** [comment]
I don't think kubescape has been used in CAPI or other sig-cluster-lifecycle projects; it was our own initiative to introduce it.

My opinion is that it's not worth reintroducing unless we intend to act on the warnings it produces. The goal would be to fix those that need fixing and skip those we don't intend to fix, then fail the job (probably a nightly job, not for each PR) if we trigger a warning.

I don't think we have resources to accomplish that, so I'd prefer to remove the [unused kubescape test spec](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/kubescape.go) and move on, but I can certainly be persuaded otherwise.

**Comment by dtzar** [comment]
Yes, I'd vote to remove and cleanup until there is a specific driving use-case for it (like a flavor which enables/tests compliance).
