### ISSUE TITLE
Book has documentation for features not yet released

### ISSUE THREAD

**Issue by mjnovice** [kubernetes-sigs/cluster-api-provider-azure#2786]
According to the document, we can specify vnets in a separate `resourceGroup` but that doesn't seem to be the case.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/3083824/200424217-21cd38e8-d6af-4376-a80a-104d74a09003.png">

**Comment by CecileRobertMichon** [comment]
The book is currently published from the main branch. This feature is available in the main branch but not yet in the latest release (release ETA is this week https://github.com/kubernetes-sigs/cluster-api-provider-azure/milestone/28).

**Comment by mjnovice** [comment]
@CecileRobertMichon thanks for the clarity, however I see that in the same doc we are referring to 
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/3083824/200425736-10444a43-f5fd-4f7e-af7e-a0880cd495c0.png">
1.2.4, is that just by chance ?

**Comment by CecileRobertMichon** [comment]
@mjnovice not sure I agree that those two things are in the same doc: one screenshot seems to be coming from https://capz.sigs.k8s.io/ while the other is part of https://cluster-api.sigs.k8s.io/user/quick-start.html, those are two different Netlify websites with each their own publishing pipeline

Since the book is meant to be user-facing, it makes sense to change the default to point to the latest release docs.

**Comment by mjnovice** [comment]
Sure, thanks @CecileRobertMichon again for the clarification.

**Comment by CecileRobertMichon** [comment]
/retitle Book has documentation for features not yet released

**Comment by CecileRobertMichon** [comment]
Previous discussion on the topic for CAPI: https://github.com/kubernetes-sigs/cluster-api/issues/6017

**Comment by mjnovice** [comment]
@CecileRobertMichon added my thoughts on the thread.

**Comment by dtzar** [comment]
We now have the process to only update the book website for what is current for the last shipped version of CAPZ.  The documentation in the main repo itself contains docs for whatever is current in the code repo which gets published at minor release.

It would be nice to have a versioned website, but this is quite a bit of work and out of scope for this issue.  

Closing since this is technically resolved now.
