### ISSUE TITLE
AzureManagedCluster E2E: Scale node pools

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#2854]

**Comment by nojnhuh** [comment]
@jackfrancis Since the e2e tests already include ["manual" scaling of the node pools](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/388f66f3643d3f68e3a3d616341e08f055a1d69f/test/e2e/aks.go#L375), is the goal of this issue to test more of the autoscaling behavior? e.g. spinning up lots of pods and making sure the node pools scale in/out as appropriate? Or was there something else you had in mind?

**Comment by nojnhuh** [comment]
Resolved in #2765
/close
