### ISSUE TITLE
AzureManagedCluster E2E: node pool Name CRUD

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-provider-azure#2856]
/kind feature
/area managedclusters

**Describe the solution you'd like**
E2E tests for node pools with the NAME CRUD operations.

**Comment by jackfrancis** [comment]
Deliverables:

1. Test "create" `additionalTags` against both system and user node pool.
2. Test "update" `additionalTags` against pools, and against `AzureManagedControlPlane` as well
3. Test "delete" `additionalTags` against pools and `AzureManagedControlPlane`

@CecileRobertMichon I assume #3 is fine for `AzureManagedControlPlane`?, in other words, the tags that we define in our test template "buildProvenance", "creationTimestamp", and "jobName") aren't required in any way and we can delete them in an E2E scenario?

**Comment by nojnhuh** [comment]
@jackfrancis Do those details better fit #2866?

For this issue, what exactly would it mean to "create" a node pool name if all node pools must already have a name?

**Comment by jackfrancis** [comment]
Yep, moved the comment over!

(I'll delete from here.)

**Comment by nojnhuh** [comment]
Sounds good. I'll start working on that one and unassign myself here for now in case anyone wants to pick this up in the meantime.
/unassign

**Comment by nojnhuh** [comment]
I've been experimenting with changing the `spec.name` of an AzureManagedMachinePool and see some unexpected behavior. Specifically, when I change the name from `pool` to `jon1`, a new node pool is created, then `pool1` is scaled to zero **but never deleted**. Then after renaming `jon1` back to `pool1`, the existing `pool1` stays at zero replicas and `jon1` is scaled to zero, so ultimately the MachinePool shows none of its replicas are available but is still ready.

I think the simplest workaround for now is to enforce that `spec.name` is immutable in the webhook so users don't run into this. Does that seem reasonable? AKS doesn't seem to expose any way to directly change the name of a node pool, so that seems consistent with how we handle other fields.

**Comment by nojnhuh** [comment]
Chatted with Jack and Cecile, I'll plan to make `spec.name` immutable and backport that change to the release branches. Would still be interesting to learn more about exactly what's going on here.

**Comment by nojnhuh** [comment]
Back to the original intent to test the node pool name e2e, @jackfrancis do you have an opinion on concretely what a test might do here since the field is immutable? To me it seems like the most we can reasonably do is verify that the value specified in the AzureManagedMachinePool is correctly applied to the node pool according to AKS, but I wonder if that's already covered enough by the unit tests here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/207ff80443e55db9a7e3857fe51da46842e4b99e/azure/services/agentpools/spec_test.go.

**Comment by jackfrancis** [comment]
I think what we'd do is add to this PR: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2925

But since we don't have consensus to move forward w/ those changes I think UT are the best in the meantime, until we agree to land the above and/or we invest in an envtest spike to do integration tests using a local apiserver instance (not a full cluster).

**Comment by nojnhuh** [comment]
Sounds good. Since this is already covered by unit tests and we're not going to move forward with that PR for now, it looks like there aren't any changes to make for this issue. Should we close this or keep it open to track testing this with something beyond unit tests like e2e or envtest?

**Comment by jackfrancis** [comment]
close!
