### ISSUE TITLE
Fix Ginkgo v2 deprecation warnings in e2e runs 

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes-sigs/cluster-api-provider-azure#2903]
/kind bug

**What steps did you take and what happened:**
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2773 uplifts Ginkgo to v2 and CI logs are full of mostly 2 types of deprecation warnings:

1. *Fixed* ~~[Measure()](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-measure)~~:
```
 You're using deprecated Ginkgo functionality:
=============================================
  Measure is deprecated and will be removed in Ginkgo V2.  Please migrate to gomega/gmeasure.
  Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-measure
    /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/conformance_test.go:99 
 To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=2.5.0 

```
Suggested migration strategy: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#migration-strategy-1

2. [CurrentGinkgoTestDescription](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-currentginkgotestdescription)():
```
 You're using deprecated Ginkgo functionality:
=============================================
    CurrentGinkgoTestDescription() is deprecated in Ginkgo V2.  Use CurrentSpecReport() instead.
  Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-currentginkgotestdescription
    /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/helpers.go:421
    /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/common.go:270
    /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/common.go:273
    /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/helpers.go:421
To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=2.5.0 

```
Suggested migration strategy: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#migration-strategy-4

**What did you expect to happen:**
No Ginkgo deprecation warnings are emitted in the CI runs.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
@mboersma already suggested almost ready fix for the 1) deprecation warning in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2773#issuecomment-1334406151. This as is or with small changes (see why it might need a change [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2773#issuecomment-1336135051)) should be enough to fix the first part of the issue. 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Sajiyah-Salat** [comment]
please close this issue if this soved.

**Comment by mboersma** [comment]
This issue is only halfway fixed: the warning `CurrentGinkgoTestDescription() is deprecated in Ginkgo V2` can still be seen in all our e2e runs. Please feel free to open a PR that fixes that and closes this issue, it would be very much appreciated.

**Comment by Sajiyah-Salat** [comment]
Ohk, got it. Can you please guide me through the file where changes is needed.

**Comment by mboersma** [comment]
@Sajiyah-Salat since it's complaining about a specific function, we can probably just search the codebase to find where it's used and replace it:

```shell
% git grep CurrentGinkgoTestDescription
test/e2e/common.go:     if CurrentGinkgoTestDescription().Failed {
test/e2e/common.go:     Logf("Cleaning up after \"%s\" spec", CurrentGinkgoTestDescription().FullTestText)
test/e2e/helpers.go:    text := CurrentGinkgoTestDescription().TestText
```

Then, visiting the suggested link in the error message (https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-currentginkgotestdescription), we're told `CurrentGinkgoTestDescription()` has been replaced by `CurrentSpecReport()`. 

We can start by simply replacing the one string with the other and then [running the e2e tests](https://cluster-api.sigs.k8s.io/developer/testing.html#running-the-end-to-end-tests-locally) to see if there are compilation errors. The explanation suggests that it returns a `types.SpecReport`, so it may not act exactly as before and we may need to call its helper methods.

I hope that helps, but please let me know if you have more questions. Thanks!

**Comment by Sajiyah-Salat** [comment]
I am a beginner and dont have any information about ginko or azure. though I understand the issue. But i think this issue needs code contribution. Am I eligible to solve this issue.

**Comment by Sajiyah-Salat** [comment]
should I replace ``CurrentGinkgoTestDescription`` with `` CurrentSpecReport()`` in common.go and helper.go ?

**Comment by mboersma** [comment]
I think replacing `CurrentGinkgoTestDescription()` with `CurrentSpecReport()` is the first thing to try.

But the [docs](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-currentginkgotestdescription) suggest that `CurrentSpecReport()` returns something different--the "full-fledged `types.SpecReport`." So just replacing one with the other may not work.

There may be compilation errors, which you can find by running the e2e tests as described above. If so, probably there is function call or property of the `SpecReport` object that replaces whatever function we were previously calling on the return value of `CurrentSpecReport()`. This is where you'd need to look through Ginkgo docs to find the replacement.

**Comment by Sajiyah-Salat** [comment]
Phewww... Lots of work. is it really a good first issue?

**Comment by Sajiyah-Salat** [comment]
/assign
I got it. I am new to azure. I have understanding of aws. Let me know how can I run e2e tests. Do I need to have azure? Steps would be helpful.

**Comment by mboersma** [comment]
Great! You can run the e2e tests for this CAPZ project this way:

https://capz.sigs.k8s.io/developers/development.html#e2e-testing

You should have Azure credentials in order to run the tests.

**But** since one of the first things the `./scripts/ci-e2e.sh` script does is compile the test code, it might be enough to set fake values for `AZURE_CLIENT_ID` and the others, then run the tests. If you see compilation errors after you make the changes we talked about above, then you can work on fixing those and assume that when everything compiles, you can submit a PR.
