### ISSUE TITLE
AZs should not get enabled by default if the user selected Azure region does not support them

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#294]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Deployed a cluster in southcentralus without specifying an `availabilityZone` property.
Got error:
```
I1007 22:52:02.452034       1 azuremachine_reconciler.go:216] Selecting first available AZ as no availability zone was set or user-provided availability zone is not supported for VM size Standard_B2ms in location southcentralus
I1007 22:52:02.452089       1 azuremachine_reconciler.go:220] Selected availability zone 2 for cluster-1007-b-controlplane-0
E1007 22:52:03.042859       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AzureMachine VM: failed to create vm cluster-1007-b-controlplane-0 : failed to create or get machine: cannot create vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"ResourceTypeNotSupportAvailabilityZones\" Message=\"The resource type 'virtualMachines' does not support availability zones at location 'southcentralus' and api-version '2019-03-01'.\""  "controller"="azuremachine" "request"={"Namespace":"default","Name":"cluster-1007-b-controlplane-0"}
```

**What did you expect to happen:**
I would expect the "default" control plane config to work in every region without requiring the user to have knowledge about which Azure features are supported in what region (especially since the user isn't explicitly enabling said feature).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Supported regions for availability zones: https://docs.microsoft.com/en-us/azure/availability-zones/az-overview

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@justaugustus

**Comment by justaugustus** [comment]
Opened this to track on the Azure side: https://github.com/Azure/azure-sdk-for-go/issues/5968

**Comment by justaugustus** [comment]
I've added a workaround in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/295. 
Once it merges, we should close this but continue to watch the upstream issue.

**Comment by justaugustus** [comment]
Validated https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/295 works with `southcentralus`, our offending location.

**Comment by Drewm3** [comment]
@CecileRobertMichon  and @justaugustus, I have tracked down the API based workaround that can be applied here. The recommendation is to use the Get Providers API that is documented here: https://docs.microsoft.com/en-us/rest/api/resources/providers/get. 

This will show the zone for each region in which the specific provider, Microsoft.Compute in this case, is mapped. If there are no mappings such as in the case for South Central US, then the service is not supported for zonal deployments. 

As you may have guessed the situation in South Central US is due to the fact that AZs are starting to be brought online in South Central US, but they are not available to the public yet. During this transition period there was investigations into just suppressing the VM sizes in the SKU API for public customers; However due to some challenges in the implementation of the SKU API it was found to be difficult to suppress the zones in the SKU API, and the guidance is to use the Provider API to ensure zones are supported for the specific namespace.

Please let me know if you have any questions. Otherwise I will resolve this issue if there is no other questions.

**Comment by justaugustus** [comment]
@Drewm3 -- I'll take a look and let you know. Thanks for investigating! :)
