### ISSUE TITLE
Add ServiceHealth to AzureManagedCluster Status

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#3001]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Now that #2738 is done to incorporate resource health in AzureManagedCluster,  we should also add Service Health status.

Service Health documentation: https://docs.microsoft.com/en-us/azure/service-health/service-health-overview
Service Health (Events) API: https://docs.microsoft.com/en-us/rest/api/resourcehealth/events/list-by-single-resource#events
**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nojnhuh** [comment]
Assuming [this](https://learn.microsoft.com/en-us/rest/api/resourcehealth/2022-05-01/events/list-by-single-resource?tabs=HTTP) is the exact endpoint we'd hit to get this data, it looks like that only exists in the 2022-05-01 version of the API, but the 2020-05-01 version is currently the latest one included in the latest version of the Go SDK (both tracks 1 and 2). Since I don't think new API versions are being added to the track 1 SDK, I think we'll have to block this on our migration to track 2 (#2670).

@CecileRobertMichon Does that seem acceptable to wait until then or do you think we'll need to integrate Service Health before we're on track 2 of the SDK?

**Comment by CecileRobertMichon** [comment]
> Does that seem acceptable to wait until then

@nojnhuh yes

cc @dtzar
