### ISSUE TITLE
VMSS deleted and recreated when AzureMachinePool ProvisioningState status field is Failed

### ISSUE THREAD

**Issue by jamesgoodhouse** [kubernetes-sigs/cluster-api-provider-azure#3087]
/kind bug

**What steps did you take and what happened:**
There are likely multiple ways to enter into this condition, but this happened to us via the following path:
1. cluster-autoscaler scales up a VMSS, increases capacity field
2. the new VM(s) fail to bootstrap and join the cluster
3. The Azure VMSS treats that as a terminal failure, and sets its `provisioningState` field to `Failed`
4. Next `Reconcile()`, CAPZ reads that field and writes it into the `BootstrapSucceeded` condition
5. Then it hits [this case in the switch](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/9b2bf83f9077747306d233b647557a34fac9e87e/exp/controllers/azuremachinepool_controller.go#L317-L322) which triggers CAPZ to delete the VMSS and recreate it.

**What did you expect to happen:**
I would expect this state to be logged and for an event to be recorded

**Anything else you would like to add:**
N/A

**Environment:**

- cluster-api-provider-azure version: `v1.7.0`
- Kubernetes version: (use `kubectl version`): `v1.21.14`

**Comment by CecileRobertMichon** [comment]
@jamesgoodhouse I believe this behavior is by design as it allows remediating failed instances in the absence of support of [MachineHealthChecks](https://cluster-api.sigs.k8s.io/user/concepts.html#machinehealthcheck) for MachinePools. This might be change soon with MachinePoolMachines being added in CAPI to allow deleting specific instances.

Can you please expand on your use case, why the current behavior doesn't work well and what you'd like to see instead? If we just log/emit an event for the failed machine instance, that means it would stay around and never get reconciled/fixed, do you rely on another way of dealing with failed instances? 

cc @mboersma @devigned @Jont828

**Comment by dthorsen** [comment]
👋 Chiming in because I asked @jamesgoodhouse to open this issue and PR a fix.

The current behavior results in the forcible and sudden deletion of potentially dozens of healthy node VMSS instances without draining them, and severe workload disruption in the cluster just to remediate even a single failed bootstrap. 

I could see doing some of this logic on the AzureMachinePoolMachine for instance and deleting just failed instances, but deleting the entire VMSS is most certainly worse in the majority of cases. 

If you use cluster-autoscaler, it actually cleans this up eventually, because after a failed scale up it will eventually time out and scale the VMSS back down to where it was, and the VMSS (as I understand it) will delete the failed instances on scale-down first.

**Comment by CecileRobertMichon** [comment]
> I could see doing some of this logic on the AzureMachinePoolMachine for instance and deleting just failed instances, but deleting the entire VMSS is most certainly worse in the majority of cases.

I missed that it was deleting the entire VMSS, I assumed it was just deleting the failed instance 😮 that's indeed disruptive...

I think what we really want is deleting failed instances? whether that's autoscaler, CAPZ controller, of CAPI MachineHealthChecks

**Comment by dthorsen** [comment]
I suspect that should be fairly simple logic to add to azuremachinepoolmachine's controller. Makes sense to me.

**Comment by jamesgoodhouse** [comment]
So looks like the code isn't getting an accurate view of the state of the instances. For example, an instance can come up in Azure marked as `Succeeded` for the Azure Provisioning State, but the CAPZ bootstrap extension can be failed. CAPZ currently is not accounting for the bootstrap extension status. I can get access to it in the payload CAPZ relieves from Azure, so that's not a problem, but I'd like some guidance on if this status should be considered separate from the VMSS ProvisioningState, or roll it up into the ProvisioningState and considered it Failed if the BootstrapState is failed.

**Comment by CecileRobertMichon** [comment]
@jamesgoodhouse I think we can use what standalone VMs are doing currently as model: 

A) The VM provisioning state determines the `VMRunning` condition https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/virtualmachines/virtualmachines.go#L95
B) The bootstrap extension provisioning state determines the `BootstrapSucceeded` condition https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machine.go#L569

The overall `Ready` condition is a summary of all other conditions https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machine.go#L633, meaning if either a) or b) is "False", overall `AzureMachine` overall `Ready` status should be `false`.

**Comment by jamesgoodhouse** [comment]
I've added in [setting of the condition for bootstrapping](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3096/files#diff-aa35ad63e0c0fcfc3b7d35fc6305a1f8ffbcfae38349f10bab8052a955ea4178R284-R295). I also added in a [check of this condition during reconciliation](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d82fbd0b9db28d2ed01c7248aa166d63b09513d9/exp/controllers/azuremachinepoolmachine_controller.go#L284-L294) to determine whether to delete the VM or not. I'm uncertain if this is the correct direction, or if it makes sense to just set the condition and wait on deleting until machine health checks can be implemented. Looks like there's work on this [here](https://github.com/kubernetes-sigs/cluster-api/pull/7938). What would be your preference?

Also, I did find some code stubs for setting the `BootstrapSucceededCondition` condition ([here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/baaa53ecab810c56cd80815b92030ada4dd2e7a4/azure/scope/machinepool.go#L461-L482) and [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/baaa53ecab810c56cd80815b92030ada4dd2e7a4/azure/scope/machinepool.go#L461-L482)), but they do no appear to be called anywhere.

**Comment by CecileRobertMichon** [comment]
> or if it makes sense to just set the condition and wait on deleting until machine health checks can be implemented. Looks like there's work on this https://github.com/kubernetes-sigs/cluster-api/pull/7938. What would be your preference?

my preference would be for waiting and delegating to the health checks so that we're not enforcing delete in the controller / doing anything that might surprise users and isn't consistent with how Machines/AzureMachines behave, but I could be convinced. We could also implement the delete temporarily and remove it once the MachinePoolMachine work is done and support for HealthChecks is added. @mboersma @Jont828 do you have any thoughts on this?

> Also, I did find some code stubs for setting the BootstrapSucceededCondition condition ([here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/baaa53ecab810c56cd80815b92030ada4dd2e7a4/azure/scope/machinepool.go#L461-L482) and [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/baaa53ecab810c56cd80815b92030ada4dd2e7a4/azure/scope/machinepool.go#L461-L482)), but they do no appear to be called anywhere.

I had the same realization on Friday when looking this code to give you pointers and opened #3114 as a result :)

**Comment by jamesgoodhouse** [comment]
@CecileRobertMichon The PR has been updated to remove the deletion of the VM and should be ready for review.
