### ISSUE TITLE
Add tracing and metrics - Open Telemetry 

### ISSUE THREAD

**Issue by rbitia** [kubernetes-sigs/cluster-api-provider-azure#311]
/kind feature
Add tracing and metrics with Open Telemetry so CAPZ is observable. 
Logging cluster provisioning metrics which will eventually export to Azure monitor. 

cc. @devigned

**Comment by justaugustus** [comment]
I think this should be a wider Cluster API discussion as opposed to a capz one.
Thoughts @vincepri @ncdc @detiber?

/priority important-longterm
/milestone next

**Comment by ncdc** [comment]
We have a CAPI issue: https://github.com/kubernetes-sigs/cluster-api/issues/1477. Maybe rally discussion there?

**Comment by vincepri** [comment]
There is lots of context in the CAPI issue that @ncdc linked. If folks here want to start on implementing metrics now and bring back the findings, that sounds good to me.

**Comment by rbitia** [comment]
@devigned do you have some time to split this issue out into size-able chunks? Feel free to open new issues or list them out here.

**Comment by devigned** [comment]
Will do.

**Comment by devigned** [comment]
Things to collect?
- Success / failure of Azure Resource (possibly available from Azure SDK for Go metrics)
  - AzureCluster
    - resource group
    - route table
    - network security group
    - vnet
    - subnet
    -load balancer (internal / external)
  - AzureMachine
    - virtual machine
    - network interface
    - public IP
    - disk
    - availability zone
- Machines / Cluster / State
   - research into labels or other ways to slice data
- Duration of deployment
- Time since last reconcile for a given AzureMachine / AzureCluster
- Duration of reconcile
