### ISSUE TITLE
Use azure managed identities to authenticate 

### ISSUE THREAD

**Issue by rbitia** [kubernetes-sigs/cluster-api-provider-azure#312]
/kind feature

Move from using service principals to azure managed identities to authenticate.
 https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

**More detail coming**

**Comment by justaugustus** [comment]
Needs to be scoped.
@juan-lee suggesting User Assigned MSI instead of System-assigned, due to ease of mgmt for the Kubernetes use case.

We need to document this recommendation, before coding it up.

**Comment by jadarsie** [comment]
Azure Stack does not have managed identities, I would selfishly suggest not to remove support for SPNs.

**Comment by alexeldeib** [comment]
Some thoughts:

- It's easy to figure out whether the user has provided any valid authentication credentials, or if MSI is available.
- We really only need two types of auth: msi, and client app/secret. 
- @jadarsie it looks like the [recommended way](https://github.com/Azure/go-autorest/blob/3492b2aff5036c67228ab3c7dba3577c871db200/autorest/azure/environments.go#L212-L221) of picking up the stack environment is by setting `AZURE_ENVIRONMENT_FILEPATH` and loading the file? 
- Is IMDS available in Stack environment? I know it's in all cloud envs. Would be nice to wire this up so the user doesn't even need to provide the details. Otherwise, we can probably add something like `AZURE_CLOUD_ENVIRONMENT` which should be mapped to [these values](https://github.com/Azure/go-autorest/blob/3492b2aff5036c67228ab3c7dba3577c871db200/autorest/azure/environments.go#L34-L39).
- We should probably use env specific authorizers by default
- It seems like the preference has been for env vars over sdk auth file or manually parsed flags. Okay by me.

To stay as compatible as possible with existing behavior, I suggest what I consider the least surprising behavior:
- If user specifies client app or secret, we expect both, and fail to validate.
- If user specifies cloud environment without both client app and secret, we fail to validate (MSI does not require this variable, so we could ignore it, but I prefer explicitly failing the user for providing this combination).
- If user provides all of client app, secret, and environment, we use the environment to load the authorization details via the SDK
  - fail in Stack if `AZURE_ENVIRONMENT_FILEPATH` is unspecified
  - fail in general if `AZURE_CLOUD_ENVIRONMENT` is non-empty and invalid.
  - default to AZUREPUBLICCLOUD
- If user provides both client app and secret, we auth to AZUREPUBLICCLOUD
- If user specifies nothing at all, we default to MSI. 

Examples:
```bash
# default, public cloud cluster with managed identity
AZURE_ENVIRONMENT_FILEPATH=""
AZURE_CLOUD_ENVIRONMENT=""
AZURE_CLIENT_ID=""
AZURE_CLIENT_SECRET=""
```

```bash
# gov cloud with managed app
AZURE_ENVIRONMENT_FILEPATH=""
AZURE_CLOUD_ENVIRONMENT="AZUREUSGOVERNMENTCLOUD"
AZURE_CLIENT_ID=""
AZURE_CLIENT_SECRET=""
```

```bash
# public cloud cluster with manual client app
AZURE_ENVIRONMENT_FILEPATH=""
AZURE_CLOUD_ENVIRONMENT=""
AZURE_CLIENT_ID="foo"
AZURE_CLIENT_SECRET="bar"
```

```bash
# works for Stack environment
AZURE_ENVIRONMENT_FILEPATH="/foo/bar"
AZURE_CLOUD_ENVIRONMENT="AZURESTACKCLOUD"
AZURE_CLIENT_ID="foo"
AZURE_CLIENT_SECRET="bar"
```

```bash
# FAILS, Stack requires filepath
AZURE_ENVIRONMENT_FILEPATH=""
AZURE_CLOUD_ENVIRONMENT="AZURESTACKCLOUD"
AZURE_CLIENT_ID="foo"
AZURE_CLIENT_SECRET="bar"
```

```bash
# FAILS, env provided with nothing else (or explicitly fail stack without sp)
AZURE_ENVIRONMENT_FILEPATH=""
AZURE_CLOUD_ENVIRONMENT="AZURESTACKCLOUD"
AZURE_CLIENT_ID=""
AZURE_CLIENT_SECRET=""
```

```bash
# FAILS, public cloud cluster missing manual app
AZURE_ENVIRONMENT_FILEPATH=""
AZURE_CLOUD_ENVIRONMENT=""
AZURE_CLIENT_ID=""
AZURE_CLIENT_SECRET="bar"
```

**Comment by jadarsie** [comment]
Sorry @alexeldeib, I missed this.

> @jadarsie it looks like the recommended way of picking up the stack environment is by setting AZURE_ENVIRONMENT_FILEPATH and loading the file?

Correct, that's how AKSe works today

> Is IMDS available in Stack environment?

Not really, limited and it does not include MSI.

> We should probably use env specific authorizers by default

In Stack's case, we also need to set `AZURE_AD_RESOURCE`

I think `AZURE_CLOUD_ENVIRONMENT` [should be](https://github.com/Azure/go-autorest/blob/master/autorest/azure/auth/auth.go#L50) `AZURE_ENVIRONMENT`

**Comment by CecileRobertMichon** [comment]
keep open

**Comment by devigned** [comment]
I'm happy to pair on this. I've spent a fair amount of time on Managed Identities, AAD and the SDKs.

**Comment by CecileRobertMichon** [comment]
@nader-ziada do you still want to try looking into this one?

**Comment by nader-ziada** [comment]
I was going to work on it later this week or next week, but I'm okay if someone else is ready to get started on it

**Comment by nader-ziada** [comment]
@devigned feel free to take over if you would like, I can pick up something else. Thanks

**Comment by devigned** [comment]
[WIP doc](https://docs.google.com/document/d/17o3uDJmsYlzfaC00K0dzYOaYin04zew853VYYxW2vhc/edit#) that @nader-ziada and I have been working on. Probably get it fleshed out today.

**Comment by nader-ziada** [comment]
@devigned for the user managed identity, would the user have to create the identity first and pass it along in the cluster yaml? or would the we actually create it?

**Comment by devigned** [comment]
For user assigned identities, there are a couple routes.
1. The identity could be created out of band, [possibly using Azure CLI](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-manage-ua-identity-cli#create-a-user-assigned-managed-identity) or other flow, and assigned the desired roles. The identity or identities would then need to be specified by name in the `AzureMachine` or `AzureMachinePool` specs.
2. It would be possible to have the manager create the user assigned identity. I could imagine creating a new CRD which would represent this identity and the roles requested for the identity. Instances of this resource could referenced from `AzureMachine` and `AzureMachinePool` specs.

**Note**: VM and VMSS support assigning multiple user assigned identities to machines. The `AZURE_CLIENT_ID` env var should contain the `CLIENT_ID` of the identity to be used via the Azure SDK for Go. The CLIENT_ID will be used by the SDK to request a token from the IMDS service running on the VM.

**Comment by jseely** [comment]
@devigned are the Managed Identities only used for the cloud controller manager?

They aren't being used for the management cluster to provision workload clusters, are they?

**Comment by devigned** [comment]
Managed Identities are not currently used in the cloud controller manager, but they definitely could be. I would go as far as to say they should be the preferred identity for cloud controller manager in environments that support managed identities.

We _must_ also support Service Principal credentials.

**Comment by ncdc** [comment]
Will we be able to test all the various auth options in CI?

**Comment by devigned** [comment]
@ncdc, we will be able to test for workload clusters no problem. Testing a control plane cluster would be a little odd. I think we would want to create a workload cluster, then pivot control plane to that cluster since managed identity would only be available in the Azure provisioned machines.

Does that make sense?

**Comment by ncdc** [comment]
Yes, that makes sense. Thanks. I'd imagine we'd want to test all the relevant scenarios for:

- Bootstrap cluster (not running in Azure)
- Workload cluster
- Management cluster running in Azure

**Comment by devigned** [comment]
After discussing with @CecileRobertMichon, we would like to propose the following:
- scope user assigned identities to only "bring your own identity"
- add an array of identities to AzureVirtualMachine

Something like:
```go
type Identity struct {
    ProviderID string `json:"providerID"`
}

type AzureVirtualMachine struct {
    // ....
    UserAssignedIdentities []Identity `json:"userAssignedIdentities,omitempty"`
    // ....
}
```

AzureVirtualMachine should validate that if `VMIdentity == "UserAssigned"`, the `UserAssignedIdentities` array is populated with at least one identity.

The ProviderID for the identity should be set by a user to indicate the resource is already created and should not be created or otherwise managed by the controller.

In the future, we will likely change the `ProviderID` to be optional, and add to the `Identity` struct to allow for creation of identities.

**Comment by CecileRobertMichon** [comment]
@devigned s/AzureVirtualMachine/AzureMachineSpec no?

**Comment by devigned** [comment]
</ninja edit> @CecileRobertMichon what do you mean.

**Comment by devigned** [comment]
Also, if those field / struct names offend any senses, please offer changes. They were off the cuff.
