### ISSUE TITLE
Unable to use a Image from Compute Gallery

### ISSUE THREAD

**Issue by rahulgupta999** [kubernetes-sigs/cluster-api-provider-azure#3223]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
- Created a custom Azure VM Image by using Cluster API image Builder
- Referenced the image in AzureMachineTemplate by using computeGallery parameters
- CAPZ provider fails to provision a VM instance with the error:
"error"="failed to reconcile AzureMachine: failed to reconcile AzureMachine service virtualmachine: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"InvalidParameter\" Message=\"Cannot specify user image overrides for a disk already defined in the specified image reference.\" Target=\"storageProfile\""

**What did you expect to happen:**
The control plane and machine nodes should have come up with expected Image.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 1.7
- Kubernetes version: (use `kubectl version`): 1.24.6 
- OS (e.g. from `/etc/os-release`):  windows server 2022, ubuntu-20

**Comment by nawazkh** [comment]
@rahulgupta999 I was able to build an Azure Custom Image using Cluster API image Builder and bring up a CAPZ workload cluster using `AzureMachineTemplate` as specified in [Using Azure Compute Gallery (Recommended)](https://capz.sigs.k8s.io/topics/custom-images.html?highlight=custome#using-azure-compute-gallery-recommended). 

Although I did run into below error while applying the image, but unfortunately, it was **not** the error mentioned in the description of the issue. 
My AzureMachine complained saying 
```
failed to reconcile AzureMachine: failed to reconcile AzureMachine service virtualmachine: failed to create resource azure-cni-v1-9235/azure-cni-v1-9235-control-plane-45jct (service: virtualmachine): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="GalleryImageNotFound" Message="\"The gallery image /subscriptions/<ahem ahem>/resourceGroups/cluster-api-images/providers/Microsoft.Compute/galleries/ClusterAPI1678238939ylfi/images/capi-ubuntu-1804-1678239006/versions/0.3.1678239006 is not available in eastus region. Please contact image owner to replicate to this region, or change your requested region.\"" Target="imageReference"
```

It was because the ubuntu image name displayed on `make build-azure-sig-ubuntu-1804` has the version suffixed to the name, which when put into AzureMachine template throws an error. 

```
OSType: Linux
ManagedImageResourceGroupName: cluster-api-images
ManagedImageName: capi-ubuntu-1804-1678239006
ManagedImageId: /subscriptions/<ahem ahem>/resourceGroups/cluster-api-images/providers/Microsoft.Compute/images/capi-ubuntu-1804-1678239006
ManagedImageLocation: eastus
ManagedImageSharedImageGalleryId: /subscriptions/<ahem ahem>/resourceGroups/cluster-api-images/providers/Microsoft.Compute/galleries/ClusterAPI1678238939ylfi/images/capi-ubuntu-1804/versions/0.3.1678239006
```

I was able to solve it by using `capi-ubuntu-1804` in AzureMachine as my image name.

**Comment by mboersma** [comment]
/close

@rahulgupta I just re-tested this similarly to what @nawazkh described above, and things seem to work with my Compute Gallery and a CAPZ k8s v1.27.1 cluster without problems. I followed the Image Builder and CAPZ docs and modified the "default" template in Tilt to include the `image:` section necessary.

I'm going to close this issue, but please reopen if we've missed something or if you're still seeing the problem described here. Thanks for reporting bugs! 🐛
