### ISSUE TITLE
Support User Identity in CAPZ managed AKS Cluster

### ISSUE THREAD

**Issue by Ishani-Gupta** [kubernetes-sigs/cluster-api-provider-azure#3239]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently, only system managed identity is supported on CAPZ managed AKS cluster for **control plane identity**. Based on your current use case, it would be great to have user managed identity support in AKS cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Code path where we hard code identity to system managed identity: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/managedclusters/spec.go#L273

**Environment:**

- cluster-api-provider-azure version:  1.7.2
- Kubernetes version: (use `kubectl version`):  
- OS (e.g. from `/etc/os-release`):

**Comment by xiujuanx** [comment]
I ever investigated AzureClusterIdentity. So I am interested in this issue. I will work on this issue.

/assign xiujuanx

**Comment by Ishani-Gupta** [comment]
@xiujuanx  I can pick up the fix too but since I have never ever worked on the repo , it would take me longer time.
instead, can help in pr review. Thanks!

**Comment by shyamreddy333** [comment]
Dear Team, we are moving towards to use User managed assigned identities instead of SPN due to security wave. 

Initially we tried the using the custom config file which is having the the below config followed from https://capz.sigs.k8s.io/topics/identities.

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: example-identity
  namespace: default
spec:
  type: UserAssignedMSI
  tenantID: <azure-tenant-id>
  clientID: <client-id-of-user-assigned-identity>
  allowedNamespaces:
    list:
    - <cluster-namespace>
    
    we are getting the following error with the above config 
    
    Error: cluster.cluster.x-k8s.io/capz-n-5273-92569-2-l4xhka4 created
2024-07-22T10:39:21.2997611Z Error from server (InternalError): error when creating "./capzcluster-post.yaml": Internal error occurred: failed calling webhook "default.azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io": failed to call webhook: Post "https://capz-webhook-service.capz-system.svc:443/mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremanagedcontrolplane?timeout=10s": no endpoints available for service "capz-webhook-service"
    
   And our expected config should have the below config with UMI instead of using Service principal.
   
   clusterctl generate cluster $clusterName \
--kubernetes-version $CAPZ_WORKLOAD_K8S_VERSION \
--control-plane-machine-count=3 \
--worker-machine-count=3 > capzcluster.yaml

Could somebody help with the custom file which can be assign the UMI to the respective worker machines and control plane to access.

Much appreciate your help, Thanks!
