### ISSUE TITLE
Add unit tests for azure/pointers.go

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#3291]
/kind cleanup

**Describe the solution you'd like**
Add unit tests for the [`azure/pointers.go`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/pointers.go) file. The goal is to reach at least 80% code coverage for `pointers.go`.

**Anything else you would like to add:**
This is a part of a larger effort to reach 60% code coverage in CAPZ.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by PiotrLewandowski323** [comment]
Hi,
I started working on this issue, but I'm not sure what's the expected behaviour for the  [StringMapPtr](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/pointers.go#L31)  function when the argument is nil. The comment says it returns nil, but I think that it returns a pointer to an empty map.

**Comment by willie-yao** [comment]
Hi! Thanks so much for working on this issue. That's a good catch.. I think the comment is incorrect and that the intended behavior is that it returns a pointer to an empty map. Otherwise, there would be a nil pointer dereference on this [line](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/agentpools/spec.go#L355) Would you be able to change the comment in your PR?
