### ISSUE TITLE
Run codecov job for each PR and display message if code coverage is lower than before

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#3312]
/kind feature

**Describe the solution you'd like**
As it was mentioned in this [issue comment](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3229#issuecomment-1470825135), it is good practice to use the previous code coverage % as a baseline. Currently, the code coverage job only runs on each new commit to `main`. It would be helpful to our code coverage practices to run the codecov job for each PR before it is merged, and displaying a reminder message if the code coverage is decreased. This way, we're not allowing regression of the quality of code for new contributions.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Adding the comment I brought up in office hours here: rather than enforcing minimum test coverage before we have a secure baseline, I would recommend starting with just adding visibility on each PR's test coverage. Enforcing not decreasing test coverage in theory is a good idea but in practice could lead to ineffective unit tests just to "meet the bar" or discouraging new contributors from opening PRs on code that has zero existing tests.
