### ISSUE TITLE
Remove v1alpha3 and v1alpha4 from CAPZ

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#3393]
/kind cleanup

**Describe the solution you'd like**
With the release of CAPI v1.4.0, the v1alpha3 and v1alpha4 APIs have been deprecated. Starting with CAPI v1.5, the k8s API server will stop serving the `v1alpha3` version. We should remove them from CAPZ as they will be removed from CAPI soon. 

**Anything else you would like to add:**
More details on the deprecation timeline here: https://cluster-api.sigs.k8s.io/contributing#removal-of-v1alpha3--v1alpha4-apiversions

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
One thing we were discussing in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3380 is that as part of this work we should repurpose the apiversion upgrade test (https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-apiversion-upgrade-main) to do a CAPI and CAPZ upgrade but within v1beta1 to ensure backwards compatibility (instead of from v1alpha4 to v1beta1) so for example: create a cluster with CAPI v1.0.x and CAPZ v1.0.x and upgrade both to the main branch (or the current branch if it's a PR test). Another option would be to test only the last version upgrade, i.e. create a cluster with the latest release of CAPI and CAPZ then upgrade both to main (or the current branch if it's a PR test).

**Comment by willie-yao** [comment]
@CecileRobertMichon Would it be sufficient for this issue to refactor the test to upgrade from the oldest version of v1beta1 to the latest release instead of main? I think that there is value in having both a test that upgrades to the latest v1beta1 version and main/current branch. I would love to implement both, but it may take me more time and could be separated into a different issue/PR.

**Comment by CecileRobertMichon** [comment]
@willie-yao the current test already upgrades to the current branch the test is running on. I think it would be both easier and most valuable to do that (from any v1beta1 older release) as it would allow us to run it in PRs to catch regressions (and as a periodic job on main). A job that tests a past release to the latest release would be static since the release doesn't get updated once it's released so there wouldn't be much value in running it more than once and if it did catch an issue it would be too late as the release would already be out. Does that make sense?

**Comment by willie-yao** [comment]
Ah that makes sense! I was unaware that the current test upgrades to the most recent branch. Is it because the version the test upgrades to is defined here using the local manifests? https://github.com/willie-yao/cluster-api-provider-azure/blob/remove-old-api/test/e2e/config/azure-dev.yaml#L95

**Comment by CecileRobertMichon** [comment]
yes @willie-yao that's exactly right

**Comment by willie-yao** [comment]
I have added a test from v1.0=>current. To reduce the scope of the current PR, I'll add additional tests for newer versions => current in a separate PR. 

This is how CAPI handles it: https://github.com/kubernetes-sigs/cluster-api/blob/main/test/e2e/clusterctl_upgrade_test.go#L129
