### ISSUE TITLE
securityRules doesn't got cleaned up on Azure side

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes-sigs/cluster-api-provider-azure#3395]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

By creating a workload cluster and defining a bunch of `securityRules` (to restrict access to the API-Server on a network level), it's possible to mutate `azurecluster.spec.networkSpec.subnets.securityGroup.securityRules`.

But changes in the `securityRules` list don't get propagated to Azure. In this case, the `controlplane-nsg` still has old entries defined.

**What did you expect to happen:**

Beside Azure default securityRules i only expect the same rule set as stored in the `azurecluster` CR.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The current implementation (see [`azure/services/securitygroups/spec.go`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/aac91265c698bb64943f14024b5e751b385581ae/azure/services/securitygroups/spec.go#L71-L81)) doesn't update security groups.

Not really relevant but maybe worth to mention here as well:
It's also not possible to define a `deny` rule through CAPZ ([`azure/converters/rules.go`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/aac91265c698bb64943f14024b5e751b385581ae/azure/converters/rules.go#L35-L36))

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
pasting from the slack thread:

is it that the code is only adding new rules but not deleting existing ones if they are removed from the CR? If so this is a similar issue we had with tags (cc @nojnhuh)

The main issue is that once the user deletes the rule there is no way to know "this rule used to be specified but no longer is" in the reconcile unless we have some other way of tracking what was previously applied (for tags we use an annotation). We can't just PUT the rules specified because we don't want to delete rules created by external processes (eg. cloud-provider-azure, user defined policies, etc.)

Rules themselves also don't have tags (since they are a nested resource) so we can use tags to identify "rules owned by capz" from the rest.
