### ISSUE TITLE
Add missing test coverage for azuremachinetemplate_webhook.go

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#3429]
/kind cleanup

**Describe the solution you'd like**
Currently, `azuremachinetemplate_webhook.go` is missing unit tests in the following areas:

- [ValidateCreate()](https://app.codecov.io/github/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremachinetemplate_webhook.go#L56) needs to be tested for the following cases:
  - spec.RoleAssignmentName != ""
  - (r.Spec.Template.Spec.NetworkInterfaces != nil) && len(r.Spec.Template.Spec.NetworkInterfaces) > 0 && r.Spec.Template.Spec.SubnetName != ""
  - (r.Spec.Template.Spec.NetworkInterfaces != nil) && len(r.Spec.Template.Spec.NetworkInterfaces) > 0 && r.Spec.Template.Spec.AcceleratedNetworking != nil
  - networkInterface.PrivateIPConfigs < 1

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by samyakjain10** [comment]
@willie-yao I see a test already for `RoleAssignmentName` which seems to be titled incorrectly. It is actually a test for `SystemAssignedIdentityRole`.

Here is the reference of that test https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremachinetemplate_webhook_test.go#L131. Should I correct the name for this test as well, so that things are clearer?

**Comment by willie-yao** [comment]
> @willie-yao I see a test already for `RoleAssignmentName` which seems to be titled incorrectly. It is actually a test for `SystemAssignedIdentityRole`.

@samyakjain10  Great catch!! This was left over from when we deprecated `RoleAssignmentName` and transferred the variable to `SystemAssignedIdentityRole`. It would be great if you could correct the name for the test. Thanks so much!
