### ISSUE TITLE
Egress on existing clusters using node load balancer breaks after v1.9.x upgrade

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api-provider-azure#3664]
/kind bug

**What steps did you take and what happened:**

If a cluster is not using NAT gateways for the nodes after upgrading CAPZ to `v1.9.2` or `v1.9.3` new VMs no longer have egress to the Internet and never join the cluster.

1. Deploy an older version of CAPZ
```
clusterctl init --infrastructure azure:v1.8.5
```
2. Generate a cluster spec:
```
clusterctl generate cluster capi-quickstart \
  --kubernetes-version v1.27.2 \
  --control-plane-machine-count=1 \
  --worker-machine-count=2 \
  > capi-quickstart.yaml
```
3. Remove the `natGateway` config for the worker nodepool in `AzureCluster`. Should look something like:
```
  networkSpec:
    subnets:
    - name: control-plane-subnet
      role: control-plane
    - name: node-subnet
      natGateway:
        name: node-natgateway
      role: node
    vnet:
      name: capi-quickstart-vnet
```
4. Create the cluster `kubectl apply -f capi-quickstart.yaml` and follow the Quick Start to deploy [CPI](https://cluster-api.sigs.k8s.io/user/quick-start.html#install-a-cloud-provider) and [CNI](https://cluster-api.sigs.k8s.io/user/quick-start.html#deploy-a-cni-solution).
5. Upgrade CAPZ to `v1.9.2` or `v1.9.3` 
```
clusterctl upgrade apply --infrastructure azure:v1.9.3
```
6. Update the AzureCluster object in any way.
```
kubectl annotate azurecluster capi-quickstart updated=dkoskin
```
This results in the a new NAT Gateway getting created, but it never gets attached to the existing subnet.
```
      - cidrBlocks:
        - 10.1.0.0/16
        id: /subscriptions/<subscription>/resourceGroups/capi-quickstart/providers/Microsoft.Network/virtualNetworks/capi-quickstart-vnet/subnets/node-subnet
        name: node-subnet
        natGateway:
          id: /subscriptions/<subscription>/resourceGroups/capi-quickstart/providers/Microsoft.Network/natGateways/capi-quickstart-node-natgw-1
          ip:
            name: pip-capi-quickstart-node-natgw-1
          name: capi-quickstart-node-natgw-1
```

![image](https://github.com/kubernetes-sigs/cluster-api-provider-azure/assets/4969231/bd659031-4e59-4d46-b2e9-3ba3463cf4ac)
7. Scale up the node MachineDeployment and observe the new Node does not come up
```
kubectl scale md capi-quickstart-md-0 --replicas=3
```
Cloud init logs:
```
[  360.442475] cloud-init[1278]: [2023-06-24 05:29:11] Cloud-init v. 23.1.2-0ubuntu0~22.04.1 running 'modules:final' at Sat, 24 Jun 2023 05:29:11 +0000. Up 41.72 seconds.
[  360.449713] cloud-init[1278]: [2023-06-24 05:29:17] [preflight] Running pre-flight checks
[  360.453556] cloud-init[1278]: [2023-06-24 05:34:29] error execution phase preflight: couldn't validate the identity of the API Server: Get "https://capi-quickstart-a2a9441a.westus.cloudapp.azure.com:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[  360.459773] cloud-init[1278]: [2023-06-24 05:34:29] To see the stack trace of this error execute with --v=5 or higher
[  360.459849] cloud-init[1278]: [2023-06-24 05:34:29] 2023-06-24 05:34:29,555 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
[  360.459910] cloud-init[1278]: [2023-06-24 05:34:29] 2023-06-24 05:34:29,555 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
[  360.459969] cloud-init[1278]: [2023-06-24 05:34:29] Cloud-init v. 23.1.2-0ubuntu0~22.04.1 finished at Sat, 24 Jun 2023 05:34:29 +0000. Datasource DataSourceAzure [seed=/dev/sr0].  Up 360.37 seconds
```

**What did you expect to happen:**
IMO existing clusters not already using a NAT Gateway for node egress should not be modified and continue not to use it, unless a user explicitly creates a new subnet.

**Anything else you would like to add:**
I see this change was made in `v1.9.0` [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3365), but I didn't observe this behavior until trying with `v1.9.2` with [this PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3554).

**Environment:**

- cluster-api-provider-azure version: 
`v1.9.2`
- Kubernetes version: (use `kubectl version`): 
Tried with: `v1.27.2` and `v1.26.5`
- OS (e.g. from `/etc/os-release`): 
Default Ubuntu 22.04 image

**Comment by CecileRobertMichon** [comment]
@dkoshkin I have two proposals for you:

1) We change the defaulting to not update existing subnets: https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/eac62d2804f8a8447f533121505c094bf8499a65
This is a bit of a hack because it relies on the `ID` field to determine that the defaulting is happening on an existing subnet vs a new subnet. Ideally, NAT Gateway would be a pointer so we could differentiate between disable NAT Gateway and new cluster, and we could have simply switch the default from empty string to default name, but that is not the case :(

2) We update existing subnets to "attach" the new NAT Gateway: https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/b18f008599ae476ae88c0e258cf3f3d79a76603e

I'm leaning towards 2) because it's a better long-term solution. I agree with you that ideally we shouldn't touch existing cluster infra on upgrade. However, NAT Gateways are [the recommended approach](https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/default-outbound-access#if-i-need-outbound-access-what-is-the-recommended-way) for outbound connectivity on Azure and we should provide a path forward for existing clusters. 1) is a hack and may work for now but we've talked about getting rid of `ID` altogether because it's an anti-pattern (we're setting the spec from the controller, there's a comment [here](https://cluster-api.sigs.k8s.io/user/concepts.html?highlight=immut#machine-immutability-in-place-upgrade-vs-replace) about it).

Thoughts? I still need to run some tests to validate that these approaches work and write unit tests but wanted to get your input on these options.

**Comment by dkoshkin** [comment]
Thanks for the suggestions @CecileRobertMichon!

What do you think about a combination of both of these approaches? Use 1 to fix this issue without making an infra change and then use 2 and allow users to opt in to this change by changing the `spec` (is this even possible?)

**Comment by CecileRobertMichon** [comment]
@dkoshkin done, PTAL: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3700
