### ISSUE TITLE
type assertions could `panic`

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#3683]
/kind bug

**What steps did you take and what happened:**

There are at least four single-assignment Go [type assertions](https://go.dev/tour/methods/15) in webhook code which could `panic()` if passed an unexpected type. [1](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azurecluster_webhook.go#L56) [2](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azureclustertemplate_webhook.go#L59) [3](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremachinetemplate_webhook.go#L98) [4](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremanagedcluster_webhook.go#L59)

**What did you expect to happen:**

We don't see `panic()`s when running CAPZ, so presumably the actual code paths always pass objects of the expected type. But that's not defensive coding: it might be better to use the double-assignment type assertion.

```go
old, ok := oldRaw.(*AzureCluster)
if !ok {
```

Maybe this is by design, essentially stating that it would be catastrophic to receive an unexpected type. And maybe that never happens at runtime. 

Nonetheless, if it did, the current code would restart the capz-controller pod, which seems like overkill compared to handling the error.

**Comment by nojnhuh** [comment]
I don't think it's possible to manufacture this kind of scenario from a user's position since controller-runtime must have some kind of mechanisms in place to prevent other types from reaching webhooks. controller-runtime's API doesn't make it obvious though whether or not that's true though.

Checking type assertions like that though is definitely a good habit to get into.

also i :heart: permalinks:
1. https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/555ff94c3ae66d9e03ef7f41d1a081bca95bdb49/api/v1beta1/azurecluster_webhook.go#L56
2. https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/555ff94c3ae66d9e03ef7f41d1a081bca95bdb49/api/v1beta1/azureclustertemplate_webhook.go#L59
3. https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/555ff94c3ae66d9e03ef7f41d1a081bca95bdb49/api/v1beta1/azuremachinetemplate_webhook.go#L98
4. https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/555ff94c3ae66d9e03ef7f41d1a081bca95bdb49/api/v1beta1/azuremanagedcluster_webhook.go#L59

**Comment by mboersma** [comment]
/close

> controller-runtime must have some kind of mechanisms in place to prevent other types from reaching webhooks

I think this is correct, and the overwhelming pattern here and elsewhere seems to be not to check the error value on a type assertion. It's not worth changing this IMHO.
