### ISSUE TITLE
Allow authentication with Azure Workload Identity for ASO

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#3732]
Follow-up from #3526

AzureClusterIdentity resources specifying `type: WorkloadIdentity` should configure ASO to use the same Workload Identity parameters for authentication when interacting with resources for clusters associated with that AzureClusterIdentity.

**Comment by nojnhuh** [comment]
Testing this out, this should actually already work without any "real" changes to CAPZ, or at least to the Secret that gets generated for ASO. The Workload Identity test on #3723 is only failing because ASO's ServiceAccount isn't authorized:
```
"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://oidcissuercapzci.blob.core.windows.net/oidc-capzci/'. Assertion Subject: 'system:serviceaccount:capz-system:azureserviceoperator-default'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\r\nTrace ID: 6003acdd-1a4f-4e22-8d81-fb5b46c04600\r\nCorrelation ID: 29d0cca0-c49b-43e9-b0b9-957d766ca2cb\r\nTimestamp: 2023-08-14 05:06:56Z"
```

As part of this issue, we should still document that extra step in the doc added by #3770 and update our own CI config.

**Comment by adriananeci** [comment]
> Testing this out, this should actually already work without any "real" changes to CAPZ, or at least to the Secret that gets generated for ASO.

Yup, that's right because Workload Identity doesn't need any extra secret values compared with what we are currently adding into the ASO secret, see https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/controllers/asosecret_controller.go#L262-L283 for more context.

For readability, I'm looking to extend the cases statement while generating the ASO secret so that workload identity is explicitly treated in ASO secret generation logic.

> As part of this issue, we should still document that extra step in the doc added by https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3770 and update our own CI config.

I'll se how those settings can be added in CI config once the Workload Identity PR is merged.
