### ISSUE TITLE
Make Cluster CIDR Block a variable in the templates

### ISSUE THREAD

**Issue by lieberlois** [kubernetes-sigs/cluster-api-provider-azure#4067]
/kind feature

**Describe the solution you'd like**
It seems like ATM the cluster CIDRs are hardcoded to 192.168.0.0/16 in the templates. I have a use case where i want to customize this. Of course I can adjust it in the template, but I would love if I could set it using an env variable similar to CLUSTER_NAME etc. 

**Anything else you would like to add:**
I'd be happy to contribute this, however I'm not sure how the variables in the YAML templates are getting substituted. I would suggest to do something similar to `sshPublicKey: ${AZURE_SSH_PUBLIC_KEY_B64:=""}`, but when I tried it out, I didn't understand the substitution. With `envsubst` the default wasn't set properly (might be an issue with MacOS though, many shell tools behave differently on macos).

**Environment:**

- cluster-api-provider-azure version: v1.11.2
- Kubernetes version: 1.25
- OS (e.g. from `/etc/os-release`):  Linux / MacOs

**Comment by CecileRobertMichon** [comment]
@lieberlois the templates are really meant to be used for dev/testing and as reference but they can't possibly cover every use case. That being said, in this case it should be too disruptive to make CIDR blocks an environment variable. 

You're on the right track, the variables get substituted via envsubst and something like `${VARIABLE:=default_value}` should work. However I wonder if in this case it's a bit different because `cidrBlocks` is a list? Can you show me what you tried and what error you got?
