### ISSUE TITLE
Support BYOCNI by networkPlugin: none

### ISSUE THREAD

**Issue by illrill** [kubernetes-sigs/cluster-api-provider-azure#4299]
/kind feature
/area managedclusters

**Describe the solution you'd like**

Support [bring-your-own CNI](https://learn.microsoft.com/en-us/azure/aks/use-byo-cni?tabs=azure-resource-manager) by allowing a `networkPlugin` value of `none`.

**Additional information**

The ASO `ManagedCluster` created by CAPZ uses API version `containerservice.azure.com/v1api20210501`. I think we would need to be on at least `containerservice.azure.com/v1api20230201` to do this.

**Comment by CecileRobertMichon** [comment]
@illrill this should be already possible in the latest v1.12.0 release. Are you seeing otherwise?

**Comment by CecileRobertMichon** [comment]
Ah I think I see what happened... It was added in https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/74a8a2b956ae1a649083b3af7219675aed67047d#diff-4f3f78f0f7d3bc8623d0cb965b7f944f7084252c71407ca43bc5bf881acbf656R121 but lost in the rebase in https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/224b7dc26ac523579f4296261808ab861135bd6f#diff-4f3f78f0f7d3bc8623d0cb965b7f944f7084252c71407ca43bc5bf881acbf656. Both PRs merged around the same time. 

This should be fairly easy to add back by adding "none" to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/types_class.go#L100

I'm going to mark this a good first issue in case someone wants to pick it up since it's a one line change

/good-first-issue
