### ISSUE TITLE
Deploy to Multiple Subscriptions from Single Manager

### ISSUE THREAD

**Issue by jseely** [kubernetes-sigs/cluster-api-provider-azure#480]
> ⚠️ Cluster API Azure maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/YYYYMMDD-template.md) when necessary. This is to be expected for large changes that impact multiple components, breaking changes, or new large features.

***Goals***
1. Enable deployment of clusters into multiple subscriptions

***Non-Goals/Future Work***
1. Deployment of single cluster spanning multiple subscriptions
1. Deployment of clusters into multiple Tenants
1. Deployment of clusters using unique Service Principals

**User Story**

As an operator I would like to deploy clusters for independent teams into their corresponding subscriptions so that costs associated with those clusters can be attributed to the correct team via Azure Billing.

**Detailed Description**

Large Azure customers generally deploy across a number of subscriptions to enable better financial record keeping and billing for teams that may have independent finance teams. These subscriptions are managed via Management Groups to ensure that large organizations can associate policy and governance restrictions over those teams. 

Customer Central IT Kubernetes Operations teams will want to comply with their Central IT Azure Operations teams to ensure smooth and effective collaboration. 

To support this mode of operation a single CAPZ manager should be Subscription Agnostic and should instead rely on the Cluster configuration objects to specify SubscriptionID.

**Contract changes [optional]**

Remove Subscription ID fields from all components deployed with the CAPZ controller manager.
Use Subscription ID fields from all Cluster data structures

/kind proposal

**Comment by justaugustus** [comment]
cc: @CecileRobertMichon @juan-lee

**Comment by jseely** [comment]
@devigned and I paired today to understand what was necessary to implement this change.

It appears that all that would be necessary would be:
- [ ] Add `SubscriptionId` to the `AzureCluster` struct
- [ ] Pass in `AzureCluster` `SubscriptionId` to `NewClusterScope`'s `setCredential` call
- [ ] Add conversions between `v1alpha2` and `v1alpha3`

**Comment by CecileRobertMichon** [comment]
@jseely @devigned since the v1alpha3 API has already been released, we can't make any breaking changes to it (I assume the new `SubscriptionId` field would be required) unfortunately. I would say add this for v1alpha4 but since the Cluster API community decided to delay v1alpha4 I'm not sure how we should handle adding new required fields in the meantime. @vincepri any suggestions?

Otherwise, you could make `SubscriptionId` an optional field to "override" the subscription ID in the manager for a specific cluster. That way, it wouldn't be a breaking change and we can try it out for a while before making it required and moving the subscriptionID field in `AzureCluster` as part of the next API version.

**Comment by devigned** [comment]
Optional seems like a good idea for the time being.

**Comment by jseely** [comment]
Agreed optional seems fine.

**Comment by vincepri** [comment]
Not sure familiar with the concept of a Subscription, is it fair it say that it maps to an GCP project more or less? If that assumption is correct, and by default the manager has a subscription id (how does it get this?), having an optional field on Cluster is the way to go if you want to support this multi-tenancy behavior in v1alpha3.

**Comment by devigned** [comment]
It's tough to make a direct analogy since a project in GCP has a lot of opinions about networking and resource relationships built into it.

A resource in Azure must be within a Subscription and a Resource Group. There is a bit of defaulting done within a resource group, but nothing at the level of a GCP project. Resource groups are just a convenient way to group resources. An Azure Subscription has role based authorization and billing concepts built into it.

Resource URI: `https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}`. 

Sub and RG combined would probably closest to mapping to a GCP project.
