### ISSUE TITLE
kubectl and cluster version are different in conformance tests

### ISSUE THREAD

**Issue by chewong** [kubernetes-sigs/cluster-api-provider-azure#579]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
"Client Version: version.Info{Major:\"1\", Minor:\"19+\", GitVersion:\"v1.19.0-alpha.2.232+a26c34e47007df\", GitCommit:\"a26c34e47007dfa26378a7fac5296763df476d11\", GitTreeState:\"clean\", BuildDate:\"2020-04-29T16:22:24Z\", GoVersion:\"go1.13.9\", Compiler:\"gc\", Platform:\"linux/amd64\"}

Server Version: version.Info{Major:\"1\", Minor:\"19+\", GitVersion:\"v1.19.0-alpha.2.215+4099ad6e0db5d7\", GitCommit:\"4099ad6e0db5d79d48bc29f28622ab9c70c02303\", GitTreeState:\"clean\", BuildDate:\"2020-04-28T19:58:25Z\", GoVersion:\"go1.13.9\", Compiler:\"gc\", Platform:\"linux/amd64\"}\n"
```

from https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-conformance-master/1255572470396620807. That's probably because the kubernetes repo checked out by prow and [https://dl.k8s.io/ci/k8s-master.txt](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/scripts/ci-conformance.sh#L74) isn't the same.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
we're using https://dl.k8s.io/ci/k8s-master.txt because of  https://github.com/kubernetes/release/issues/897 

https://dl.k8s.io/ci/latest-green.txt has the latest master commit but the artifacts might not exist yet and it would fail to pull the binaries and images if that's the case.

What we can do in the meantime:

- git checkout the commit we get from k8s-master.txt before building k8s binaries
- do nothing and wait for https://github.com/kubernetes/release/issues/897 to be resolved, knowing that kubectl and cluster version might be slightly different in the meantime.

cc @detiber since capa is most likely hitting this as well.

**Comment by neolit123** [comment]
found this ticket by searching the org by mistake.

afaik, k8s-master is/ being removed:
https://github.com/kubernetes/test-infra/pull/18517

i have not seen the issue described in release recently and the kubeadm/kinder jobs have been using ci/latest:
https://github.com/kubernetes/release/issues/897#issuecomment-668665847

**Comment by CecileRobertMichon** [comment]
Thanks @neolit123, we actually changed to ci/latest a few days ago https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/845 so I believe this one can be closed.

/close
