### ISSUE TITLE
Add support for Azure Dedicated Hosts 

### ISSUE THREAD

**Issue by rbitia** [kubernetes-sigs/cluster-api-provider-azure#675]
/kind feature

Add support for Azure Dedicated Hosts (ADH) and eventually when those are able to scale with VMSS add that preview feature so folks can scale their ADH. 

Some users have a need for isolated servers and this support would support their use-case. 

I'm also curious how we would enable this specific offer type, is it a feature flag or something else?

**Comment by alexeldeib** [comment]
anyone know what this entails?

**Comment by CecileRobertMichon** [comment]
I haven't looked into this too much but I believe to get started:
- add new service for hosts
- add a knob to the AzureMachine spec to use dedicated hosts (possibly with options if their are attached configurations)
- when ADH is enabled, create the host before creating the VM in the azuremachine reconciler then add the host details to the VM Create
- tests
- sample flavor template
- documentation

basing my interpretation of how ADH works on https://docs.microsoft.com/en-us/azure/virtual-machines/linux/dedicated-hosts

I might work on this once I'm mostly done with the refactors if no one else has picked it up by then.

**Comment by CecileRobertMichon** [comment]
FYI @dklyle in case he has any comments/feedback since I know his team has been trying ADH with capz recently.

**Comment by dklyle** [comment]
@CecileRobertMichon was out last week. There is also work around a service for host groups and being able to specify those in the AzureMachine spec as well. I have started work on generalizing my implementation for dedicated host support. But I'm a ways from having it ready to post as a PR. 

Ideally once, if, the ability to specify host group instead of specific host is implemented in the Azure VM API, the code would get much simpler and just keep the host group part.

**Comment by CecileRobertMichon** [comment]
I'm going to move this to the next milestone for now thanks @dklyle 

/milestone next
