### ISSUE TITLE
Azure resource names do not follow conventions

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#678]
We should audit resource names in CAPZ to ensure that we are following [best practices](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging).

Beyond following convention, not naming resources properly can lead to issues: Since `{CLUSTER_NAME}` is being used in a lot of places to name Azure resources. However, these resources have their own validation rules. So even if the K8s cluster resource can have a name up to 253 chars, we need to validate that it will be short enough to be appended to a suffix or prefix for any other resource where it is used, such as `${CLUSTER_NAME}-node-routetable`, 
`${CLUSTER_NAME}-control-plane-2`. We should enforce validation on resource names. For example, some resources cannot contain special characters such as `.`. For those, we should either 1) not rely on `$CLUSTER_NAME` or 2) enforce the same validation on `CLUSTER_NAME`.

Note that changing names of resources might be a breaking change in some cases where we look for a resource by name without storing its ID in Spec (eg. load balancers) so we need to be careful about handling backwards compatibility.

See also https://kubernetes.slack.com/archives/CEX9HENG7/p1590166717280400

**Comment by CecileRobertMichon** [comment]
cc @devigned @asatish

**Comment by devigned** [comment]
unassigned for the time being

**Comment by nader-ziada** [comment]
here are some of the relevant info I've gathered so far from [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules)

```
virtual machine max is 64
Can't use: \/"'[]:|<>+=;,?*@& 
Can't start with underscore. Can't end with period or hyphen

routeTables	max is 80	
Alphanumerics, underscores, periods, and hyphens.
Start with alphanumeric. End alphanumeric or underscore

virtual networks max 64
Alphanumerics, underscores, periods, and hyphens.
Start with alphanumeric. End alphanumeric or underscore

resourcegroups max is 90
Alphanumerics, underscores, parentheses, hyphens, periods, and unicode characters that match the regex documentation.
Can't end with period.
```
and since the longest suffix we use when creating a VM can be `control-plane-2kw67` and the VM has a shorter max length than other resources, we need the `CLUSTER_NAME` to have a max of 44 characters to support the current naming of `{CLUSTER_NAME}-control-plane-2kw67`. The `CLUSTER_NAME` would also need to follow the same rules for VM name which are the most strict

a `CLUSTER_NAME` was a max of 44 characters would not cause issues with other resources such as 
 - resourcegroup = `{CLUSTER_NAME}`
 - vnet = `{CLUSTER_NAME}-vnet`
 - subnet = `{CLUSTER_NAME}-controlplane-subnet`
 - routetable = `{CLUSTER_NAME}-controlplane-routetable`

the other outstanding question is whether we also want to change default names to match the [recommended naming for components](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging#recommended-naming-components) which uses a prefix such as: 
 - `rg-{CLUSTER_NAME}` for resource group 
 - `vnet-{CLUSTER_NAME}` for virtual networks
 -  `snet-{CLUSTER_NAME}` for subnets
 - `route-{CLUSTER_NAME}` for route tables
 - `vm<policy name or app name><###>` for VMs


@CecileRobertMichon @devigned any thoughts?

**Comment by devigned** [comment]
Hmm... What about DNS names? I believe we could end up with a cluster name which will not create a proper DNS entry due to having a `.` in the name.

+1 to making cluster name most strict. If someone opens an issue about needing to have char set for `metadata.name`, then perhaps, we can consider adding an override for cluster name to the `AzureClusterSpec`.

**Comment by nader-ziada** [comment]
> Hmm... What about DNS names? I believe we could end up with a cluster name which will not create a proper DNS entry due to having a `.` in the name.

yeah, more restrictions on the `{CLUSTER_NAME}`
