### ISSUE TITLE
[e2e] machines should have accelerated networking enabled if supported 

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-azure#706]
**Describe the solution you'd like**
An e2e test to validate that on a workload cluster, machine types that support accelerated networking has it enabled 

more info here: https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-powershell#supported-vm-instances

**Comment by mboersma** [comment]
Note that the English heuristic in the Microsoft docs is incomplete and it's still necessary to make an API call to know the accelerated networking capability of a given SKU. For a test, we should probably just use a set of canonical SKUs for which we already know whether or not they support accelerated networking, rather than reimplement the API call.

Or maybe the test could use `az`? Here is an Azure CLI command with JMESPath filter that shows the acceleratedNetworking status of all SKUs a subscription can see:

```shell
az vm list-skus -o json \
  --query '[? starts_with(name, `Standard`) && !ends_with(name, `Promo`)].{name: name, caps: capabilities[? name==`AcceleratedNetworkingEnabled`]}[].{sku: name, acceleratedNetworking: caps[0].value}[? acceleratedNetworking != null]'

```

**Comment by nader-ziada** [comment]
i think it makes sense to use SKUs for which we already know whether or not they support accelerated networking
