### ISSUE TITLE
Audit cloud provider config

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#773]
We should go through the values in Azure.json and evaluate if:

- the default values are sane according to the cloud provider documentation: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/cloud-provider-config.md
- Do we need to set the file for both nodes and control planes (I suspect it might just be needed for control planes)
- How to simplify the UX for setting AZURE_JSON_B64

**Comment by alexeldeib** [comment]
Based on my current understanding, we do need this file on all nodes, but they may be different if desired (e.g., it doesn't appear to be required to use any credentials, msi or otherwise, on worker nodes).

Kubelet seems to require the cloud provider interface to fetch node addresses (maybe other things, that's all I went looking for): https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cloudresource/cloud_request_manager.go#L91 As vmss in a single cluster may be in different subnets, I believe the subnet field may also be different, for example.

We can disable kubelet identity on workers when using instance metadata for the same purpose: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/cloud-provider-config.md#run-kubelet-without-azure-identity

---

KubeadmConfig requires azure json, Machine and KCP require KubeadmConfig. Kubeadm config references the secret by name. If the secret does not exist, or another error occurred trying to fetch it, we requeue: https://github.com/kubernetes-sigs/cluster-api/blob/49f88d511f9584cb37bd38522a869ceaea9f2242/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L609-L614

---

One way to simplify this is have users only provide the credentials as a secret. They never see the expanded JSON. A quick and dirty approach would be to have AzureCluster take a credentials field, and on cluster reconcile we generate e.g. `azure-json-control-plane` secret. We could check for existence to avoid overwriting a user-provided custom value. We could also generate a different file for workers, watching AzureMachineTemplate events. A lot of the json fields can be derived -- vnet comes from AzureCluster directly, loadBalanceResourceGroup too. We can detect vmType from AzureMachine/AzureMachinePool.

Once we generate the file, the rest of the controllers should fall into order

**Comment by nader-ziada** [comment]
I like the idea of the cluster control generating the azure.json file and creating the secret for it

**Comment by alexeldeib** [comment]
- securityGroupName is used to add NSG rules when users create services type=LoadBalancer
- subnetName is used as the default subnet for ILB services when no subnet is explicitly provided
- primaryAvailabilitySetName and primaryScaleSetName are both unnecessary with SLB, because we can have large heterogeneous backend pools.
- vmType can always be vmss for mixed VMAS/VMSS clusters. VM without AZ or AS will have minor issues but generally (?) work okay.

all the resource groups are pretty self explanatory. for our purposes they're all the same usually, but they can be different. I'd say users who want that can currently generate their own azure.json secrets.

I think most of the other fields are fairly clear and/or defaults make sense (but we could default them explicitly). LMK what you all think

**Comment by alexeldeib** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/815
