### ISSUE TITLE
AzureMachineTemplate location template.spec property has no effect

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#868]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

It appears that the only operable "location" configuration is in the AzureCluster spec. There is a "location" property for the AzureMachineTemplate spec, but changing it has no effect. 

**What did you expect to happen:**

I actually expected the machine to be deployed in a different region, which would have been very cool! :)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Let's mark the Machine Spec `Location` property as `DEPRECATED` (see AvailabilityZone for an example).

Since it's not being used we'll mark it as deprecated to preserve back compat and remove it completely as part of v1alpha4 unless we implement the functionality to have VMs in different regions by then. It's probably non trivial though since the AzureCluster networking infra is all tied to the cluster location. 

/help
/good-first-issue

**Comment by cpanato** [comment]
it is opening for some time. 
I will take and work on this.
/assign
/remove-help
