### ISSUE TITLE
Defaulting for internal loadbalancer ip address should be moved to a webhook

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#892]
/kind feature

**Describe the solution you'd like**
The internal loadbalancer ip address default is in the Service instead of a webhook where other defaults are set:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/92164bbf8c1ae7073c7d3f63ade6cb9c9335f971/cloud/services/loadbalancers/loadbalancers.go#L196-L204

This logic should be moved to a webhook for defaulting

**Anything else you would like to add:**
Could move the logic to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/api/v1alpha3/azurecluster_default.go

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
I think the main reason it's not is that it calls to the vnet client to check IP address availability in order to find an available IP in the subnet, which can't be done from a webhook: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/services/loadbalancers/loadbalancers.go#L205
